### ISSUE TITLE
Is there any example code?

### ISSUE THREAD

**Issue by ThoDuyNguyen** [neuhausi/canvasXpress#1]
How could I test this library.
Kind regards

**Comment by neuhausi** [comment]
Install it as described in web page and the run

R
library(canvasXpress)
?canvasXpress

That will give you  many examples.

**Comment by MatthewRalston** [comment]
Since there is rich documentation on both the R manpage and on the canvasXpress.org page, should this issue be closed @neuhausi?

**Comment by ThoDuyNguyen** [comment]
I closed the issue.
