### ISSUE TITLE
is possible to customize menu names?

### ISSUE THREAD

**Issue by CarlosAndres12** [neuhausi/canvasXpress#100]
Hi.

I want to build an app for a non English speaking  public, is there a way to change the names in the menu buttons?.
![image](https://user-images.githubusercontent.com/8310276/93009346-6dafae80-f545-11ea-89ae-e919c35c548a.png)

Thanks.

**Comment by neuhausi** [comment]
Unfortunately no. Lo necesita en español? Déjeme ver si puedo convertir todo los menús a español.
Isaac

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CarlosAndres12** [comment]
Si, justamente lo necesito en español. Infórmame por favor si puedo ayudarte en algo.

**Comment by neuhausi** [comment]
Claro que sí. Ahora estoy ocupado pero yo te mando el archivo que tienes que traducir.
Gracias
Isaac

P.S. de donde eres

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CarlosAndres12** [comment]
Listo, quedo pendiente.

Soy de Colombia.

**Comment by neuhausi** [comment]
Yo también. Donde trabajas

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CarlosAndres12** [comment]
En un grupo de investigación en la universidad de Antioquia.

**Comment by neuhausi** [comment]
Hi Carlos,
Any progress in the translation?

**Comment by CarlosAndres12** [comment]
Hi, you forget to send me the file to translate.

**Comment by neuhausi** [comment]
Not possible. Sorry
