### ISSUE TITLE
implement CanvassXpress on the bioinformatics tool

### ISSUE THREAD

**Issue by garimaloh** [neuhausi/canvasXpress#103]
I am getting blank plot. Here is the code in Perl. Could you please help me implement this graph ?

[sub](url) _get_taxonomy_info {

    my ($dbproc, $sqlite_db) = @_;

    my $query = "select t.TaxonomyValue, count(*) as count from TaxonomyIndex t, UniprotIndex u where u.AttributeType = 'T' and u.LinkID =  t.NCBITaxonomyAccession group by t.TaxonomyValue order by count desc limit 1000";
    
    my %taxonomy_counter;
    my %species_counter;

    my $TOP_TAX_LEVEL = 6;
    
    my @results = &do_sql_2D($dbproc, $query);
    foreach my $result (@results) {
        my ($taxonomy, $count) = @$result;
        
        my @tax_levels = split(/;\s*/, $taxonomy);
        my $species = pop @tax_levels;
        my @top_tax_levels = @tax_levels[0..($TOP_TAX_LEVEL-1)];
        for my $level (@top_tax_levels) {
            if (! defined $level) {
                $level = "NA";
            }
        }
        
        my $top_tax_level = join("\t", @top_tax_levels);
        #print STDERR "$top_tax_level -> $species\n" if $DEBUG;
        $taxonomy_counter{$top_tax_level} += $count;
        $species_counter{$species} = $count;
        
    }

    ###################################
    ## reorganize the data for plotting
        
    my $NUM_TOP_CATS = 50;
    
    my @levels;
    for (my $i = 1; $i <= $TOP_TAX_LEVEL; $i++) {
        push (@levels, "L$i");
    }

    my @row_values;
    my @column_data;
    my $other_counts = 0;
    my $counter = 0;
    foreach my $taxonomy (reverse sort {$taxonomy_counter{$a}<=>$taxonomy_counter{$b}} keys %taxonomy_counter) {
        $counter++;
                
        my $count = $taxonomy_counter{$taxonomy};
        my @x = split("\t", $taxonomy);
        if ($counter < $NUM_TOP_CATS) {
            for(my $i = 0; $i <= $#x; $i++) {
                push (@{$column_data[$i]}, $x[$i]);
            }
            push (@row_values, $count);
        }
        else {
            $other_counts += $count;
        }
    }

    if ($other_counts) {
        # build other counts entry:
        my @columns = @column_data;
        my $first_col = shift @columns;
        push (@$first_col, "Other");
        foreach my $other_col (@columns) {
            push (@$other_col, "NA");
        }
        push (@row_values, $other_counts);
    }

    # convert column data to hash:
    my %column_data_hash;
    for (my $i = 0; $i <= $#levels; $i++) {

        my $level = $levels[$i];
        my $col_data_aref = $column_data[$i];
        $column_data_hash{$level} = $col_data_aref;
    }

    my $taxonomy_sunburst = new CanvasXpress::Sunburst("taxonomy_sunburst");
    my $plot_loader = new CanvasXpress::PlotOnLoader("taxonomy_sunburst");
    $plot_loader->add_plot($taxonomy_sunburst);
    
    my %inputs = (title =>  "Taxonomic representation of gene-level top blastx matches",

                  column_names => [@levels],

                  column_contents => \%column_data_hash,

                  row_values => [@row_values]);

    my $taxonomy_html = $taxonomy_sunburst->draw(%inputs);

    $taxonomy_html .= $plot_loader->write_plot_loader();
    
    return($taxonomy_html);
    
}

**Comment by garimaloh** [comment]
![Blank graph](https://user-images.githubusercontent.com/48873678/99319774-05b86580-281f-11eb-87e3-41249e89009c.JPG)

**Comment by neuhausi** [comment]
Can you please post the HTML page with the Javascript call to CanvasXpress please.

**Comment by garimaloh** [comment]
![calling](https://user-images.githubusercontent.com/48873678/99327662-43bd8580-282f-11eb-850a-9ca831c1e75e.JPG)

**Comment by garimaloh** [comment]
![image](https://user-images.githubusercontent.com/48873678/99328005-09a0b380-2830-11eb-9fff-3a7fd7d3e79b.png)

**Comment by neuhausi** [comment]
I mean the Javascript that calls CanvasXpress. Please see the screen where you show an error in Javascript console. I mean that script that is above

**Comment by neuhausi** [comment]
<img width="424" alt="Screen Shot 2020-11-16 at 8 27 52 PM" src="https://user-images.githubusercontent.com/254923/99328527-44174a00-284a-11eb-86ef-5540342df388.png">

**Comment by garimaloh** [comment]
Hi,

I have attached the file that make up that javascript.
________________________________

**Comment by garimaloh** [comment]
I have send a file in mail.Please check.

**Comment by neuhausi** [comment]
You will need to zip it because Github is filtering it

**Comment by garimaloh** [comment]
[Sunburst.zip](https://github.com/neuhausi/canvasXpress/files/5550876/Sunburst.zip)

**Comment by garimaloh** [comment]
These are dynamic graph we are trying to build

**Comment by neuhausi** [comment]
I know. Go to the chrome tools and copy the script. I cannot help you without the data.
Isaac

**Comment by garimaloh** [comment]
<div class="well well-sm">
                       
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/canvasXpress/29.0/canvasXpress.min.js"></script>
<script>
    var make_Sunburst_taxonomy_sunburst = function() {
    var cx = new CanvasXpress("taxonomy_sunburst", {
         "x": {
          "L1": [
                "Eukaryota","Bacteria","Eukaryota","Eukaryota","Bacteria","Bacteria","Bacteria","Bacteria","Bacteria","Bacteria","Bacteria","Bacteria","Eukaryota","Bacteria","Bacteria","Bacteria","Eukaryota","Bacteria","Bacteria","Eukaryota","Eukaryota","Bacteria","Bacteria","Bacteria","Bacteria","Eukaryota","Bacteria","Bacteria","Bacteria","Bacteria","Bacteria","Bacteria","Bacteria","Bacteria","Bacteria","Eukaryota","Bacteria","Bacteria","Bacteria","Bacteria","Archaea","Archaea","Bacteria","Bacteria","Bacteria","Viruses","Bacteria","Bacteria","Eukaryota","Other"
                       ],          "L2": [
                "Metazoa","Proteobacteria","Viridiplantae","Fungi","Firmicutes","Firmicutes","Proteobacteria","Firmicutes","Proteobacteria","Firmicutes","Actinobacteria","Proteobacteria","Metazoa","Proteobacteria","Proteobacteria","Proteobacteria","Fungi","Firmicutes","Proteobacteria","Fungi","Metazoa","Firmicutes","Proteobacteria","Proteobacteria","Proteobacteria","Amoebozoa","Cyanobacteria","Proteobacteria","Tenericutes","Proteobacteria","Proteobacteria","Proteobacteria","Proteobacteria","Cyanobacteria","Firmicutes","Fungi","Actinobacteria","Proteobacteria","Proteobacteria","Chlamydiae","Crenarchaeota","Euryarchaeota","Proteobacteria","Actinobacteria","Proteobacteria","Duplodnaviria","Proteobacteria","Proteobacteria","Metazoa",null
                       ],          "L3": [
                "Chordata","Gammaproteobacteria","Streptophyta","Dikarya","Bacilli","Bacilli","Gammaproteobacteria","Bacilli","Gammaproteobacteria","Bacilli","Corynebacteriales","Gammaproteobacteria","Ecdysozoa","Gammaproteobacteria","Gammaproteobacteria","Betaproteobacteria","Dikarya","Clostridia","Gammaproteobacteria","Dikarya","Ecdysozoa","Bacilli","Alphaproteobacteria","Alphaproteobacteria","Betaproteobacteria","Evosea","Synechococcales","Alphaproteobacteria","Mollicutes","Epsilonproteobacteria","Gammaproteobacteria","Alphaproteobacteria","Alphaproteobacteria","Synechococcales","Bacilli","Dikarya","Corynebacteriales","Epsilonproteobacteria","Betaproteobacteria","Chlamydiales","Thermoprotei","Thermococci","Gammaproteobacteria","Corynebacteriales","Betaproteobacteria","Heunggongvirae","Gammaproteobacteria","Betaproteobacteria","Ecdysozoa",null
                       ],          "L4": [
                "Craniata","Enterobacterales","Embryophyta","Ascomycota","Lactobacillales","Bacillales","Pseudomonadales","Bacillales","Alteromonadales","Bacillales","Mycobacteriaceae","Enterobacterales","Arthropoda","Pasteurellales","Vibrionales","Burkholderiales","Ascomycota","Clostridiales","Xanthomonadales","Ascomycota","Nematoda","Lactobacillales","Rickettsiales","Rhizobiales","Burkholderiales","Eumycetozoa","Prochloraceae","Rhizobiales","Mycoplasmataceae","Campylobacterales","Enterobacterales","Rhodobacterales","Rhizobiales","Synechococcaceae","Bacillales","Ascomycota","Mycobacteriaceae","Campylobacterales","Neisseriales","Chlamydiaceae","Sulfolobales","Thermococcales","Thiotrichales","Corynebacteriaceae","Burkholderiales","Peploviricota","Enterobacterales","Burkholderiales","Arthropoda",null
                       ],          "L5": [
                "Vertebrata","Enterobacteriaceae","Tracheophyta","Saccharomycotina","Streptococcaceae","Staphylococcaceae","Pseudomonadaceae","Bacillaceae","Shewanellaceae","Bacillaceae","Mycobacterium","Yersiniaceae","Hexapoda","Pasteurellaceae","Vibrionaceae","Burkholderiaceae","Pezizomycotina","Clostridiaceae","Xanthomonadaceae","Taphrinomycotina","Chromadorea","Lactobacillaceae","Rickettsiaceae","Brucellaceae","Burkholderiaceae","Dictyostelia",null,"Bradyrhizobiaceae",null,"Helicobacteraceae","Erwiniaceae","Rhodobacteraceae","Rhizobiaceae","Synechococcus","Listeriaceae","Pezizomycotina",null,"Campylobacteraceae","Neisseriaceae","Chlamydia/Chlamydophila group","Sulfolobaceae","Thermococcaceae","Francisellaceae",null,"Alcaligenaceae","Herviviricetes","Pectobacteriaceae","Comamonadaceae","Chelicerata",null
                       ],          "L6": [
                "Euteleostomi",null,"Spermatophyta","Saccharomycetes",null,null,null,null,null,"Bacillus",null,null,"Insecta",null,null,"Burkholderia","Eurotiomycetes",null,null,"Schizosaccharomycetes","Rhabditida",null,"Rickettsieae",null,null,"Dictyosteliales",null,null,null,null,null,null,"Rhizobium/Agrobacterium group",null,null,"Sordariomycetes",null,null,null,null,null,null,null,null,null,"Herpesvirales",null,null,"Arachnida",null
                       ]         },
"y": {
            "vars": [
                "myData"
             ],
        "smps": [
 "d1","d2","d3","d4","d5","d6","d7","d8","d9","d10","d11","d12","d13","d14","d15","d16","d17","d18","d19","d20","d21","d22","d23","d24","d25","d26","d27","d28","d29","d30","d31","d32","d33","d34","d35","d36","d37","d38","d39","d40","d41","d42","d43","d44","d45","d46","d47","d48","d49"   ],
"data": [
[ 80007,46313,34724,15291,14104,13689,10570,8707,8465,8413,8360,8297,7837,7751,7373,7130,7089,6510,5398,5196,4939,4592,4461,4210,4206,4184,3907,3796,3593,3480,3350,3232,3113,3015,2941,2930,2905,2839,2741,2735,2492,2462,2424,2350,2306,2239,2189,2093,2072,140386 ]
   ]
} 
}, 
{
 "axisAlgorithm": "wilkinson",
"circularRotate": -90,
"circularType": "sunburst",
"colorScheme": "Bootstrap",
"decorationFontSize": 6,
"graphType": "Circular",
"hierarchy": ["L1","L2","L3","L4","L5","L6"],
"ringsType": [
"dot"
],
"ringsWeight": [
1
],
"showTransition": true,
"subtitleFontSize": 26,
"title": "Taxonomic representation of gene-level top blastx matches",
"titleFontSize": 28,
"transitionStep": 50,
"transitionTime": 1500,
"xAxis": [
"vals"
],
"xAxisTitle": ""
});
}


    </script>

        <div>

        <canvas id="taxonomy_sunburst" width="800" height="500"></canvas>

        </div>


                 </div>

**Comment by neuhausi** [comment]
The problem is not in CanvasXpress. Here is the image with the script you sent me.
Isaac
![cX-sunburst](https://user-images.githubusercontent.com/254923/99339324-f7387100-2853-11eb-99d5-df0ce8decd33.png)

**Comment by neuhausi** [comment]
BTW,
It is very nice

**Comment by garimaloh** [comment]
Can you please help me to get this graph on local website?

**Comment by garimaloh** [comment]
Its still a blank

**Comment by garimaloh** [comment]
why its not printing the graph on the tool webpage?

**Comment by neuhausi** [comment]
Go to this page https://www.canvasxpress.org/examples/bar-1.html and drop this PNG file onto the Bar graph visualization. You will have a fully interactive webpage.
Isaac
![cX-sunburst](https://user-images.githubusercontent.com/254923/99339846-e0464e80-2854-11eb-8b4f-1e2a7f4bdd8a.png)

**Comment by neuhausi** [comment]
Is the web page in a public web site? Can I see it? I can only tell you that is not CanvasXpress since I show you the PNG whit the code you sent.
Have you check if you have two elements with the same id in the web page?
Isaac

**Comment by garimaloh** [comment]
No ,its on local host created by the tool.let me check the ids and let you know tomorrow. Thanks for all your help.

**Comment by garimaloh** [comment]
I checked the ids. no two ids are same
