### ISSUE TITLE
Circular plot with genome coordinater

### ISSUE THREAD

**Issue by seoanezonjic** [neuhausi/canvasXpress#106]
Hi @neuhausi 
I'm using the circular plot to graph variants across the genome but I use the GRCh38 build and the plot seems to use the hg19 build. Could you add this genome assembly to your plot? It would be interesting  that circular plot gives an option to set this data (in a predefined format) to use any organism/version genome.
Thank you in advance
Pedro Seoane

**Comment by neuhausi** [comment]
Absolutely. I will add it in three next version
Regards
Isaac

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: seoanezonjic ***@***.***>
Sent: Wednesday, June 23, 2021 4:09:17 AM
To: neuhausi/canvasXpress ***@***.***>
Cc: neuhausi ***@***.***>; Mention ***@***.***>
Subject: [neuhausi/canvasXpress] Circular plot with genome coordinater (#106)


Hi @neuhausi<https://github.com/neuhausi>
I'm using the circular plot to graph variants across the genome but I use the GRCh38 build and the plot seems to use the hg19 build. Could you add this genome assembly to your plot? It would be interesting that circular plot gives an option to set this data (in a predefined format) to use any organism/version genome.
Thank you in advance
Pedro Seoane

**Comment by neuhausi** [comment]
Hi @seoanezonjic 
I can't find the info for GRCh38. Can you help me with that?
I used this file in the past http://hgdownload.cse.ucsc.edu/goldenpath/hg19/database/cytoBand.txt.gz from the UCSC for the hg19

**Comment by neuhausi** [comment]
Never mind. Just replace hg19 by hg38 :-)

**Comment by neuhausi** [comment]
Added to new version 35.1
