### ISSUE TITLE
Uncaught TypeError: h[p][A][L] is null

### ISSUE THREAD

**Issue by sammyjava** [neuhausi/canvasXpress#108]
Do you have any idea what might cause "Uncaught TypeError: h[p][A][L] is null"? I'm at a loss as to what is wrong with my data. It looks fine, and used to work. Something subtle has changed with it, apparently, and I can't figure out what it is!
```
Uncaught TypeError: h[p][A][L] is null
    updateMetaData https://www.canvasxpress.org/dist/canvasXpress.min.js:429
    setMetaData https://www.canvasxpress.org/dist/canvasXpress.min.js:429
    initializeDataAttributes https://www.canvasxpress.org/dist/canvasXpress.min.js:429
    initializeData https://www.canvasxpress.org/dist/canvasXpress.min.js:429
    initializeProcessing https://www.canvasxpress.org/dist/canvasXpress.min.js:412
    initialize https://www.canvasxpress.org/dist/canvasXpress.min.js:412
    init https://www.canvasxpress.org/dist/canvasXpress.min.js:412
    CanvasXpress https://www.canvasxpress.org/dist/canvasXpress.min.js:412
    setExpressionSet https://dev.lis.ncgr.org/medicmine/bagDetails.do?scope=all&bagName=Gene+List+(Thu+Jul+01+2021+09:54:27+GMT-0600+(Mountain+Daylight+Time)):1333
    <anonymous> https://dev.lis.ncgr.org/medicmine/bagDetails.do?scope=all&bagName=Gene+List+(Thu+Jul+01+2021+09:54:27+GMT-0600+(Mountain+Daylight+Time)):1415
```

**Comment by neuhausi** [comment]
Can you please point me to the page or an example?
Thank you
Isaac

**Comment by sammyjava** [comment]
Sorry, Isaac, it's really hard to do that, it's downstream from a whole bunch of processing. I'll just try to figure it out. Was just hoping you'd seen the specific error before.

**Comment by neuhausi** [comment]
Can you share the dataset?

**Comment by sammyjava** [comment]
Well, it's dynamically generated with the code that generates the HTML. I'm pretty sure I can find it if I peel things away slowly. If I get really stuck I'll dump it and post it up here, it's pretty large.

**Comment by neuhausi** [comment]
Ok. Let me know if I can help. Did this just happen with the new version?

**Comment by sammyjava** [comment]
Yes, but it's still working on other instances, so I don't think it's a version update causing it.

**Comment by sammyjava** [comment]
Actually, we can completely ignore this -- I rebuilt the DB and now it works, and I think I had a glitch in the actual data that messed up the downstream dataset. :) Happy Tuesday! :)
