### ISSUE TITLE
the box plot in the vingette loads the incorrect data

### ISSUE THREAD

**Issue by laijasmine** [neuhausi/canvasXpress#110]
In the getting started vignette, the example box plot uses the iris dataset instead of the tooth growth dataset (mentioned in the readme) so the plot shown cannot be reproduced with the code given:

https://github.com/neuhausi/canvasXpress/blob/06ef100a7463a08c31da9d305669e160a85d3f6e/vignettes/getting_started.Rmd#L71-L77

**Comment by cb4ds** [comment]
Thanks, will be fixed in the next CRAN release!

**Comment by cb4ds** [comment]
for reference, the fix is available in version 1.35.7.9001 on the cran prep branch
