### ISSUE TITLE
[Question] Bar chart maximum width

### ISSUE THREAD

**Issue by dachia** [neuhausi/canvasXpress#111]
Hi, great library! Thanks!

Is it possible to set the maximum bar width for the bar chart?

**Comment by neuhausi** [comment]
You can adjust the bar width with the parameter widthFactor. Here are two examples:

widthFactor: 1.1

![cX-bar1](https://user-images.githubusercontent.com/254923/139595051-a8c1007b-59bf-4609-9860-8ceb8442f774.png)

widthFactor: 0.9

![cX-bar1 (1)](https://user-images.githubusercontent.com/254923/139595061-767cb2eb-0625-4df3-9ad8-81c8547b92e7.png)

**Comment by dachia** [comment]
Got it, thanks! 🙏
