### ISSUE TITLE
Boxplot problem

### ISSUE THREAD

**Issue by seoanezonjic** [neuhausi/canvasXpress#117]
Hi @neuhausi 
I'm working with data distributions and I want to build a boxplot taking into account three factors. In this way, I expect that one factor goes to series, one factor goes to grouping series and other factor goes to panels. Playing with the attributes "colorBy",  "groupingFactors" and "segregateSamplesBy"  I've obtained, the following:

![cX-obj_15_](https://user-images.githubusercontent.com/4126037/166722402-15550d0c-c12e-4668-abd8-4a370ac96913.png)

In this example, "clust_status"  goes to panels, "clust_method" goes to x boxplot axis and "source" goes to coloured series. The problem is that coloured series are not plotted and I expect a group of boxplots for each category of "clust_method". Is this possible? If so, which configuration I have to use?
Thank you in advance
Pedro Seoane

**Comment by neuhausi** [comment]
Is this what you want?
![cX-obj_15_](https://user-images.githubusercontent.com/254923/166811246-1fb13788-e96b-47b2-b30e-b50dd53b49b9.png)

**Comment by neuhausi** [comment]
I recommend also transform the data log2
![cX-obj_15_ (1)](https://user-images.githubusercontent.com/254923/166811639-cf9b700f-d454-470d-9b0c-ed48a8e3ae30.png)

**Comment by seoanezonjic** [comment]
Hi neuhasi
The example that you show me is not the layout that I'm looking for. In fact, the factor "clust_status" is lost. I show here an example for one panel:
[rank_dist.pdf](https://github.com/neuhausi/canvasXpress/files/8629398/rank_dist.pdf)
I'm looking for a boxplot with two panels with the estructure of the previous chart. One panel would represent the "raw" category and the other panel would represent the "clean" category of the factor "clust_status". Is this possible?
Thank you in advance
Pedro Seoane

**Comment by neuhausi** [comment]
You need to group the data by source, segregate by clust_method and color by source
![cX-obj_15_ (2)](https://user-images.githubusercontent.com/254923/167004975-eb03d514-00ce-44f9-9b96-4bfc12df7212.png)

Do you use R? You can call CanvasXpress with a ggplot object

library(CanvasXpress)
CanvasXpress(ggplot-object)

Let me know if this is what you want.

Isaac

**Comment by neuhausi** [comment]
If you then pivot the data by clust_status and pattern by variable then you get this
![cX-obj_15_ (3)](https://user-images.githubusercontent.com/254923/167050477-e6265e06-4613-4128-b3df-7edc748546ed.png)

**Comment by neuhausi** [comment]
Here with transformed log2 data
![cX-obj_15_ (4)](https://user-images.githubusercontent.com/254923/167050571-d7917fb5-abaf-4943-af11-679e4b2ca411.png)

**Comment by neuhausi** [comment]
If you want to see how I did it then download the picture and drop it into another CanvasXpress graph and then click on the history icon on the top toolbar. The beauty of CanvasXpress.
I think this fixes the issue?

**Comment by neuhausi** [comment]
Why do you prepend the meta data in each column?

**Comment by seoanezonjic** [comment]
The last two examples are the layout that I'm looking for. I'll explore the setting of them and I'll apply to my particular case. Respect to meta data is due to some to your examples. At beginning, I think that tag each factor  with its metadata was necessary but when I realised that is not I let the code with the tagging.
Thank you very much
Pedro Seoane

**Comment by neuhausi** [comment]
Can you please close the issue.
Thank you.
Isaac
