### ISSUE TITLE
Doubts with circular graphs

### ISSUE THREAD

**Issue by seoanezonjic** [neuhausi/canvasXpress#12]
Hi!
I'm using your great javascript library (not the R version) on my project and it's incredible how it makes easy to get charts with my data. I'm working on virus sequences and I have differents tracks of positional data. For this reason, I use your circular chart. I treat each nucleotide as a sample and I have obtained the attached image. I'm working with virus sequences about 3000-4000 nt so the rendering have a few issues. I suposse that this chart is designed to less samples (100-200) but is ideal for my work. Then I would like to make you some questions to adapt your chart to my case:

- The outer black ring is the overlapped sample names ( in this case, my virus positions). I'm interested in use the smpLabelInterval property but it is not supported on circular charts. I tried removing samples names from my data but when I want to show the links between positions, the names are missing so the link it is not shown. There is another way to do this?
- The  image shows rendering artefacts as waves and stars if you look consecutive rings. There is a way to improves the rendering quality?
- I would like to establish custom limits in barplot rings and heatmaps (in this case a common custom interval to all  heatmaps will be useful to me). How can I do this? 
- I would like to show a color scale as you use on heatmaps charts. It is posible with circular charts?
- The break length can be customised? It would be interesting in order to show correctly the ring labels.

The final image:
![cx-obj_0_circular](https://cloud.githubusercontent.com/assets/4126037/22422214/8dd4ddc8-e6eb-11e6-8584-1bfd5ae589ae.png)
I attach the json object of my chart:
[cX-obj_0_Circular.json.zip](https://github.com/neuhausi/canvasXpress/files/738811/cX-obj_0_Circular.json.zip)

Thank you very much for your help in advance.
Pedro

**Comment by neuhausi** [comment]
Let me work on it. All your suggestions make sense.
Isaac

**Comment by neuhausi** [comment]
Wow it really takes along time to render. Give me a few days and I will
give a new version that renders it in 2-3 secs and ofcourse all the other
features you mention.
Isaac

**Comment by seoanezonjic** [comment]
Thank you for your quick response to my questions and I'll be waiting for your new version. You have no idea how this features will help me to develop my project. If you need more examples or any kind of information, tell me and I'll give to you as soon I can.
Thank you so much .
Pedro

**Comment by neuhausi** [comment]
Hi Pedro,

Here is a picture with the new version of CanvaXpress I will upload later today and a summary of the changes:

1. Implemented smpLabelInterval
2. Added Color Indicator for the heatmaps
3. Changes in the layout of the data rings
4. Added mouse-over events.
5. Fixed bug in customizing the heatmap breaks.
    In this example I am using:
    "colorSpectrumBreaks" :[0.0001, 0.001, 0.005, 0.01, 0.02, 0.03, 0.04]
I am still trying to improve performance in rendering and trying to figure out why the native arc method in canvas does not produce crisp edges.

You can download the image and open it in any CanvasXpress visualization using the menus (see [http://canvasxpress.org/html/io.html](url)) for more information.

![cx-obj_0_circular](https://cloud.githubusercontent.com/assets/254923/22630415/c64bc5aa-ebc7-11e6-909d-b300628607d2.png)

**Comment by seoanezonjic** [comment]
Thank you very much for this CanvasXpress version. It handles a lot of troubles viewing my data and the circular graph is much clearer than before. I have a question, the barplot scale can be customized? I need this feature to compare two circular graphs generated in different executions.
Again, thank you by your help
Pedro

**Comment by neuhausi** [comment]
Yes you can transform the data but in this case all the data in the first ring is zero!

**Comment by seoanezonjic** [comment]
Yes, it's true but I have other samples that the barplot data is not zero. How I can modify the y limit axis on this barplot ring?
By the way, I have some doubts and suggestions with scatterplot graphs but I don't know if post them in this issue or I have to open other issue. What do you prefer?
Thank you
Pedro

**Comment by neuhausi** [comment]
Please open another issue. 
Regards
Isaac
