### ISSUE TITLE
React wrapper?

### ISSUE THREAD

**Issue by sammyjava** [neuhausi/canvasXpress#120]
I wonder if anyone (I suppose I'm included in that) would be willing to build a React wrapper for canvasXpress. I've got an environment in which React is the recommended framework, so I'm using chartjs-react: https://github.com/xr0master/chartjs-react

However, as we all know, canvasXpress is the cat's pajamas for genomic visualization, and it would be lovely to have a React wrapper for it. I have no idea how much work that is, I've never written one.

**Comment by neuhausi** [comment]
There is already one
https://www.npmjs.com/package/canvasxpress-react
Regards
Isaac

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Sam Hokin ***@***.***>
Sent: Tuesday, October 11, 2022 1:07:26 PM
To: neuhausi/canvasXpress ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [neuhausi/canvasXpress] React wrapper? (Issue #120)


I wonder if anyone (I suppose I'm included in that) would be willing to build a React wrapper for canvasXpress. I've got an environment in which React is the recommended framework, so I'm using chartjs-react: https://github.com/xr0master/chartjs-react

However, as we all know, canvasXpress is the cat's pajamas for genomic visualization, and it would be lovely to have a React wrapper for it. I have no idea how much work that is, I've never written one.

**Comment by sammyjava** [comment]
@adf-ncgr my bluegenes life just got a lot better!
