### ISSUE TITLE
how to import canvasXpress in Vue2

### ISSUE THREAD

**Issue by leiyan** [neuhausi/canvasXpress#123]
how to import canvasXpress in Vue2?
Thanks.

**Comment by neuhausi** [comment]
I have no experience working with Vue2 but I am willing to help if you share the code you are using :-)

**Comment by leiyan** [comment]
in my vue2 project, these are my steps:
1.
_npm install canvasxpress_
2.
in a vue component:
_import CanvasXpress from "canvasxpress";_
3.
then I coded following the document in js part:
new CanvasXpress("canvas", {
   "y": {
     "data": [
       [10,100,70,130,60]
     ],
     "vars": ["A"],
     "smps": ["S1","S2","S3","S4","S5"]
   }
 }, {
   "background": "rgb(255,255,255)",
   "colorScheme": "CanvasXpress",
   "graphOrientation": "vertical",
   "graphType": "Area",
   "objectBorderColor": false,
   "plotBox": false,
   "plotBoxColor": "rgb(204,204,204)",
   "showLegend": false,
   "showLegendBorder": true,
   "smpLabelRotate": 90,
   "smpTitle": "time",
   "xAxis": ["A"]
 }, false);

Then, compiling is ok, but when I opened by browser, I got error at browser console:
![image](https://user-images.githubusercontent.com/1719788/205820851-72ac3add-4f7e-44c6-95d6-8f61ee0b8d7f.png)

@neuhausi thank you so much.

**Comment by neuhausi** [comment]
Can you please include the files you are using. I am not familiar with Vue so I need a little more info. Did you look at this example with D3:
https://levelup.gitconnected.com/d3-js-and-vue-js-7a6a721eb79f

I think the template for CanvasXpress should look something like this:
```
<div>
  <canvas id={{renderTo}} width={{width}} height={{height}}><canvas>
</div>
```
I need to see you JS file.

**Comment by leiyan** [comment]
Hi @neuhausi , thank you for your help and patience. Here is the JS file (vue file):

[test.zip](https://github.com/neuhausi/canvasXpress/files/10172957/test.zip)

![image](https://user-images.githubusercontent.com/1719788/206093399-1f70d14c-a1b4-4a44-b4fe-c656c913ab65.png)

**Comment by leiyan** [comment]
@neuhausi thank you for the details. I will seriously try that tomorrow and will update.

**Comment by leiyan** [comment]
I tested two methods.

Method One:
Don't use "npm install --save canvasxpress"
And add these in "index.html":
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/canvasXpress/41.3/canvasXpress.min.css"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/canvasXpress/41.3/canvasXpress.min.js"></script>
Then if build or run, I got this error:
This dependency was not found:
canvasxpress

Method Two:
use "npm install --save canvasxpress"
add this in the src\main.js file:
import 'canvasxpress/src/canvasXpress.css'
Then add these in a vue component file:
import CanvasXpress from "canvasxpress";
"new CanvasXpress.init(...)"
**Then Method Two is working.**

**Comment by leiyan** [comment]
@neuhausi 
Thank you so much. canvasXpress is a great feature for our project.

**Comment by neuhausi** [comment]
Glad it worked. Send a link if possible.
@leiyan Please close the issue.

**Comment by leiyan** [comment]
Our project is currently private and I will provide a link when we publish it.
Thank you very much for your help. @neuhausi
