### ISSUE TITLE
Why are there regularly spaced lines in the heatmap?

### ISSUE THREAD

**Issue by leiyan** [neuhausi/canvasXpress#124]
The data is a (13826x3) matrix, and here is the config:
```
 {
          background: "rgb(255,255,255)",
          colorSpectrum: ["rgb(0,0,128)", "rgb(255,255,255)", "rgb(205,38,38)"],
          graphType: "Heatmap",
          plotBox: false,
          plotBoxColor: "rgb(204,204,204)",
          showLegendBorder: true,
          title: relationship,
          heatmapCellBox: false,
          heatmapCellBoxWidth: 0,
          heatmapCellBoxHighlightWidth: 0,
          xAxis: vars,
        },
```
And then I found there are regularly spaced lines in the heatmap, please see the output/svg. Does anyone know how to get rid of these regularly spaced lines? Thank you.

![cX-heatmap_expression](https://user-images.githubusercontent.com/1719788/206828094-2eaf4578-d224-4add-b903-3ceea90bb0a0.svg)
![WeChat Screenshot_20221209214728](https://user-images.githubusercontent.com/1719788/206828099-fd017d29-9293-405b-a8bd-8546ca04ecf1.png)

**Comment by neuhausi** [comment]
This is an anti-aliased issue. You might be able to fix it by changing the size of you canvas in your page. It usually happens when you try to draw too many lines in a small canvas. I added a little fudge factor in the new version so it is a little more resilient to this. I let you know once I release version 41.4. What is the size of the canvas in you web page? 
Here is an article that explains the issue.
https://usefulangle.com/post/17/html5-canvas-drawing-1px-crisp-straight-lines
Isaac

**Comment by leiyan** [comment]
@neuhausi 
Got it, yes, this is an anti-aliased issue.
The size of my canvas is:
width="1200" height="300"

looking forward to the new version 41.4

**Comment by neuhausi** [comment]
Use missingDataColor: "color in rgb or rgba format" in the configuration

**Comment by leiyan** [comment]
@neuhausi 
that's great, it is working very well, thank you.

https://canvasxpress.org/api/missing_data.html
[#](https://canvasxpress.org/api/missing_data.html#missingDataColor) missingDataColor

**Comment by neuhausi** [comment]
I released version 41.4. Could you please check the anti-aliased issue and close this issue if it is fixed. 
Thank you.

**Comment by leiyan** [comment]
@neuhausi 
I upgraded to version 41.4.6, but the anti-aliased issue is still.
![image](https://user-images.githubusercontent.com/1719788/207125249-9e4333b4-7db4-40f0-9bf7-98046fccd47c.png)

**Comment by neuhausi** [comment]
What is the size of the graph? 1200 X 300 px?

From: Lei Yan ***@***.***>
Date: Monday, December 12, 2022 at 1:30 PM
To: neuhausi/canvasXpress ***@***.***>
Cc: neuhausi ***@***.***>, Mention ***@***.***>
Subject: Re: [neuhausi/canvasXpress] Why are there regularly spaced lines in the heatmap? (Issue #124)

@neuhausi<https://github.com/neuhausi>
I upgraded to version 41.4.6, but the anti-aliased issue is still.
[image]<https://user-images.githubusercontent.com/1719788/207125249-9e4333b4-7db4-40f0-9bf7-98046fccd47c.png>

**Comment by leiyan** [comment]
yes, width="1200" height="300"
and y.data is (13826x3) matrix

**Comment by leiyan** [comment]
Yes, my screen has high resolution. I tested:
if display resolution is 3840x2160 and the size is 250%, then the anti-aliased issue is still;
if display resolution is 3840x2160 and the size is 200%, then the anti-aliased issue is gone.

![image](https://user-images.githubusercontent.com/1719788/207230583-719e3fe0-c015-4f9c-aefc-e5f84309109c.png)

_Do you know that you included your data in your first post?_
Yes, I know.

Thank you so much. @neuhausi
