### ISSUE TITLE
if we can customize the legend?

### ISSUE THREAD

**Issue by leiyan** [neuhausi/canvasXpress#131]
May I ask if we can customize the legend? For example, I'd like to change the legend in the top image to the legend in the bottom image. Thanks.

![Image_20230502143513](https://user-images.githubusercontent.com/1719788/235767748-843dc998-33da-4822-a8c3-029dc3aedf9a.png)

![WeChat Photo Editor_20230502143144](https://user-images.githubusercontent.com/1719788/235767763-7710a059-02db-4d50-9ebb-0f740a69c54b.jpg)

**Comment by neuhausi** [comment]
Ok. You cannot customize an 'intrinsic' legend BUT you can hide the legend and create your own. Here is a graph where the 
experiments are an intrinsic legend (that you can hide) and the Lines and Shapes are custom legends.

![cX-network5 (1)](https://user-images.githubusercontent.com/254923/236484676-1c4016ab-821b-4347-bf6c-35aa5c31d273.png)

Here is the code for those legends which should be put as part of the configuration. I will release those changes in my next version 43.6.

```
"customLegend": [
   { 
     "title": "Shapes",
     "shape": ["circle", "rectangle"],
      "shapeColor": ["rgb(255,0,0)","rgb(0,0,255)"],
      "text": ["Gene", "Protein"]
   },
   {
      "title": "Lines",
      "line": ["solid", "solid", "solid"],
      "lineColor": ["rgb(100,0,255)","rgb(125,125,125)","rgb(255,100,0)"],
      "lineWidth": ["1", "2", "3"],
      "text": ["Activate", " ", "Inhibit"]
   }
]
```

**Comment by neuhausi** [comment]
Just released version 43.6. Please check and close issue.

**Comment by leiyan** [comment]
@neuhausi 
Thank you for the quick release.

I've tested it and found that when I set “showLegend” to true, both the intrinsic legend and custom legend are displayed; when I set “showLegend” to false, neither the intrinsic legend nor the custom legend is displayed.

How do I set to hide the intrinsic legend while displaying my custom legend? Thanks.

**Comment by neuhausi** [comment]
You have more granularity to show/hide legends. Did you try `showShapeNodeLegend: false` or `showSizeEdgeLegend: false`? I don't know the type of legend you are creating please take a look and the documentation: https://canvasxpress.org/api/legends.html.
Isaac

**Comment by leiyan** [comment]
It is working now. I am using these settings:
```
showLegend: true,
showSizeEdgeLegend: false,
showColorNodeLegend: false,
showColorEdgeLegend: false,
customLegend: [
	{
	  title: "Color - spearman",
	  line: ["solid", "solid"],
	  lineColor: ["orange","purple", ],
	  lineWidth: ["5", "5"],
	  text: ["Low", "High"],
	},
	{
	  title: "Size - mi",
	  line: ["solid", "solid"],
	  lineColor: ["black", "black"],
	  lineWidth: ["1", "8"],
	  text: ["Low", "High"],
	},
],
```

Thank you so much.

![cX-canvasxpressnetwork-FLT3-Network_HSC_sig](https://user-images.githubusercontent.com/1719788/236856948-f11c6594-ca3c-4c07-81ba-80cbe41f7ae8.png)
