### ISSUE TITLE
BarLine Chart lacks the second axis tick

### ISSUE THREAD

**Issue by TheWildParamecium** [neuhausi/canvasXpress#136]
Good afternoon.

I was using the barline plot but I noticed that the second axis tick is not being displayed in the plot, despite it being formatted in the config ( "xAxis2TickFormat":"%.0f T" ). It can also be seen in the thumbnail in the right panel of plot examples that the figure used to have that second axis tick. I wonder if it could be fixed. Thank you so much for your help.

https://canvasxpress.org/examples/barline-1.html

**Comment by neuhausi** [comment]
Try:
`"xAxis2Show": true`
By default is not shown

**Comment by TheWildParamecium** [comment]
Indeed, now it is showing the second axis tick with that argument. Thank you for your help!
