### ISSUE TITLE
Doubts with scatterplots

### ISSUE THREAD

**Issue by seoanezonjic** [neuhausi/canvasXpress#14]
Hi neuhasi
As I commented in a previous issue I need to ask you some questions about scatterplots. I have the following data:
```
| X1 | Y1 | X2 | Y2 |
|  1 | 10 |  2 | 12 |
|  3 | 15 |  4 | 20 |
|  5 | 17 |  2 | 22 |
```
If I have understood the scatterplot documentation I have to set the config attributes to:
```
"xAxis": ["X1"],
"yAxis": ["Y1", "Y2"],
```
Bus, it's possible to do this?
```
"xAxis": ["X1", "X2"],
"yAxis": ["Y1", "Y2"],
```
So X axis includes X1 and X2 points but X1 is related with Y1 and X2 with Y2.
Other problem comes when I use bubble scatterplot. The size of different points is very similar between them and  I want to make it more different to reflect the magnitude that I'm plotting. I tried modifying the sizes attribute but I don't understand how it works in this chart. 
By the way, the setMaxY attribute on sccaterplot and barplot can be applied on circular graphs in a concrete ring that use this chart type?
Thank you in advance
Pedro

**Comment by neuhausi** [comment]
Yes you can do that. In this example I have:

`    "xAxis": [
      "S1",
      "S3",
      "S5"
    ],
     "yAxis": [
      "S2",
      "S4",
      "S6"
    ],`

![cx-canvas 5](https://cloud.githubusercontent.com/assets/254923/22741102/06f1b424-ede0-11e6-9bf5-6877c9e36352.png)

You can download the image and open it in any CanvasXpress visualization using the menus (see http://canvasxpress.org/html/io.html) for more information.

Also you can size the point in the Bubble plots. Could you please post a data set?

Isaac

**Comment by seoanezonjic** [comment]
Of course, here there is an example with I'm working:
[cX-obj_10_ScatterBubble2D.json.zip](https://github.com/neuhausi/canvasXpress/files/763163/cX-obj_10_ScatterBubble2D.json.zip)
Pedro

**Comment by neuhausi** [comment]
Yes. I would need to modify one method. I am in the process of publishing a new version so this change will have to wait until the next version. In the meantime, my guess is that you could transform the data in the z axis (perhaps log) to take care of that simple outlier or just take the outlier completely out. I will also add methods to remove outlier in cX.
Isaac

**Comment by neuhausi** [comment]
I made a modification but it really didn't help the situation either. Here is what I got after:

1. Remove the outlier
2. Convert freq to Covariate (sample Annotation)
3. colorBy freq
4. sizeBy freq

I will include it in the next version
![cx-canvas 6](https://cloud.githubusercontent.com/assets/254923/22841426/91a904bc-ef9f-11e6-8d86-b2b73e38f237.png)

**Comment by seoanezonjic** [comment]
The color representation was a idea that I were thinking. I tried your "recipe" and I think that it serves to my purposes. I'll try log scales also, I hope that makes the fix to my problem.
Thank you for your attention
Pedro
