### ISSUE TITLE
Drastic reduction in the font size of numbers on axis ticks

### ISSUE THREAD

**Issue by TheWildParamecium** [neuhausi/canvasXpress#144]
Good afternoon.

I noticed that there is a subtle change in the font scaling from canvasXpress.js version 45.3 to 45.4 (keeping canvasXpress.css at 45.2) whereby, in grids above a certain number of rows and columns, the font size of the numbers in the ticks are drastically reduced so that they become unreadable, and it seems to persist to this day.

![before](https://github.com/neuhausi/canvasXpress/assets/43111341/7ec069e9-7fe2-4c75-b9a1-a2828eeda0e2)
![after](https://github.com/neuhausi/canvasXpress/assets/43111341/9853601f-4836-45e9-8b4e-0118c856842c)

**Comment by TheWildParamecium** [comment]
My bad. Turns out it seems to be a change in the way the font sizes of the ticks are scaled between those two versions. My lab partner was showing me a plot that already had a scaling applied with "axisTickScaleFontFactor", and it seems that from that version it was magnified more, but increasing the value of this parameter solved the problem.

**Comment by neuhausi** [comment]
Perfect!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
