### ISSUE TITLE
NA values in heatmap tables 

### ISSUE THREAD

**Issue by juferban** [neuhausi/canvasXpress#15]
Hi Isaac,

I have a matrix where some of my cells have null values. (I am doing a t-test calculation of expression based on mutation status for a set of samples grouped by cancer type. My x axis would be the cancer type and the Y axis the Gene symbol. For some cancer types I don’t have enough samples with mutations in a particular gene so for that particular gene I have a p-value of “NA”). 
When I try to plot this data the heatmap show a loading screen and seem to get stuck there. I tried commenting out the "variables clustered" option as I know it would be problematic but I still have the same loading screen issue. 
If I remove all columns that contain at least 1 NA then it seem to work fine.

```
canvasXpress(heatmap_matrix_with_rownames, 
                         graphType='Heatmap', 
                         width=500, 
                         height=800, 
                         title=titleHM, 
                         #variablesClustered=TRUE, 
                         #samplesClustered = TRUE,
                         showSampleNames=TRUE,
                         colorSpectrum = c("green", "black", "red"), 
                         #colorSpectrumZeroValue = "White", 
                         heatmapIndicatorHeight = 40, 
                         heatmapIndicatorHistogram = TRUE, 
                         heatmapIndicatorPosition = "topLeft", 
                         heatmapCellBox = FALSE
)
```

Thanks a lot,

Julio

**Comment by neuhausi** [comment]
Hi Julio,
My bad. It is fixed now and I will include the fix in the next version. The yellow boxes are null values (NA). If you don't like yellow you can always chage the color for the missing values with the parameter missingDataColor.
Isaac
![cx-canvas 7](https://cloud.githubusercontent.com/assets/254923/22842198/63ecde92-efa2-11e6-83f3-25dffa3d5acf.png)

**Comment by neuhausi** [comment]
Please Download Version 14.1

**Comment by juferban** [comment]
Downloaded the new version and tested it setting the missing value color to white. 
Works perfect.

Thanks a lot for fixing the issue so quick.

J.
