### ISSUE TITLE
Could canvasXpress respect `theme(plot.title.position = "plot")` in ggplot2?

### ISSUE THREAD

**Issue by davidhodge931** [neuhausi/canvasXpress#150]
I would like to be able to have the title & subtitle on the far left

```
library(tidyverse)
library(palmerpenguins)
library(canvasXpress)

p <- penguins |> 
  ggplot() +
  geom_point(aes(x = flipper_length_mm, 
                 y = body_mass_g, 
                 colour = species)) +
  labs(title = "Blah", subtitle = "Blah") + 
  theme(plot.title.position = "plot")

canvasXpress(p)
```

![image](https://github.com/neuhausi/canvasXpress/assets/55065152/8f5c6e59-c7fc-42d0-bd34-525d4a670ae2)

**Comment by davidhodge931** [comment]
Less important, but it'd be great if it could respect the other similar arguments:
* theme(plot.caption.position = "plot")
* theme(legend.location = "plot")

**Comment by neuhausi** [comment]
I will honor the theme

**Comment by davidhodge931** [comment]
Awesome! If you add `theme(legend.location = "plot")`, you might need to add a minimum version of 3.5.0 to ggplot2 in your DESCRIPTION file - as this is a new feature

**Comment by neuhausi** [comment]
Fixed in 48.6. I added the caption too

```
library(tidyverse)
library(palmerpenguins)
library(canvasXpress)
p <- penguins |> 
  ggplot() +
  geom_point(aes(x = flipper_length_mm, 
                 y = body_mass_g, 
                 colour = species)) +
  labs(title = "The title of the plot", 
       subtitle = "Nice subtitle for the graph",
       caption = "Some interesting caption") + 
  theme(plot.title.position = "plot",
        plot.caption.position = "panel")

p
canvasXpress(p)
```

![cX-htmlwidget-90e981ecce132c7b688a-cx](https://github.com/neuhausi/canvasXpress/assets/254923/55b39f22-8ebd-4c77-b994-06add2ac04ce)

**Comment by neuhausi** [comment]
Can you please verify all the issues you submitted and close them.
Thank you.
Isaac

**Comment by davidhodge931** [comment]
Works great :)
