### ISSUE TITLE
Alert window when trying to draw a pie chart with one of the classes with a value of 0

### ISSUE THREAD

**Issue by TheWildParamecium** [neuhausi/canvasXpress#158]
Good morning.

I was trying to draw a pie chart with 3 classes that may range between [0-Any positive number), like the following.

![Captura desde 2024-06-11 11-13-52](https://github.com/neuhausi/canvasXpress/assets/43111341/dd05c739-4ec2-4e17-8cc6-b7f42da6b049)

But I found the following alert window when trying to draw the data inside that table:

![Captura desde 2024-06-11 11-14-09](https://github.com/neuhausi/canvasXpress/assets/43111341/1eb29855-ad29-4225-9a9c-1d0dd2ec0122)

which I think is an unexpected behavior because there is no negative number inside the table, so I think that 0 is also considered a negative number.

What I would expect as desirable behavior: To show in the legend the name of the class and the corresponding color, even if there is no representation of it in the chart footer (so that we can know that it is a class that did not have any representation in that particular representation, and in case of having another variable that is segregating in several pie charts, the same class can be seen in the other chart if it has a value greater than 0).

Another possible alternative would be for the code logic to bypass and remove from the final chart the classes with value 0 (not the ones with a negative value, which could still trigger this alert), since currently the alert window appears and the chart is not rendered.  

A snippet of the reproducible code used to generate the figure:

<code>
{
   "version": 50,
   "renderTo": "obj_0_",
   "data": {
     "y": {
       "vars": ["no_abstract","no_pmid","abstract"],
       "smps": ["row 0"],
       "data": [
         [11502451],
         [0],
         [25052979]
       ]
     },
     "x": {},
     "z": {}
   },
   "config": {
     "toolbarType": "under",
     "xAxisTitle": "x_axis",
     "title": "Pubmed articles stats",
     "objectColorTransparency": 1,
     "theme": "cx",
     "colorScheme": "CanvasXpress",
     "graphType": "Pie",
     "graphOrientation": "horizontal"
   },
   "events": false,
   "info": false,
   "afterRenderInit": [],
   "afterRender": []
}
</code>

**Comment by neuhausi** [comment]
It is because of the zero. If you convert it into a tiny number it will work ok.

**Comment by TheWildParamecium** [comment]
It could be also a possible solution to the problem. I will try it. Thank you!
