### ISSUE TITLE
Unusual distribution of the scatter2D color legend

### ISSUE THREAD

**Issue by TheWildParamecium** [neuhausi/canvasXpress#159]
Good afternoon.

I am sorry to bother again. I found the following unusual behaviour while using scatterplot2D plotting method. I was doing the same scatterplot (same code call but with different data) with different samples with a colorBy parameter using "similarity" (a variable distributed between [0-1] ). But I noticed than in one of the samples it looks like this:

![cX-obj_10_ (1)](https://github.com/neuhausi/canvasXpress/assets/43111341/fb056fe1-551c-4978-9fe3-f9ae1c0357fa)

However, in the other one, the color legend shows this unusual appearance:

![cX-obj_10_](https://github.com/neuhausi/canvasXpress/assets/43111341/99fd46b5-f8fe-4b61-84c2-c7a9e0692358)

I though it might be because I had actual similarity values of 1 in one of the samples but not the others, but I found also this behaviour in a figure in which the similarity values doesnt reach the upper limit of 1, so I am wondering how to fix it.

I was searching for CanvasXpress config parameters to try to limit the ranges of the color scale, but I did not find it.  I was wondering if there is any possible solution to the problem.

Thank you so much for your time!

**Comment by neuhausi** [comment]
No need to apologize. That is a bug that will be fixed in the next version. Thank you.

**Comment by neuhausi** [comment]
Fixed in 50.3
![cX-bad](https://github.com/neuhausi/canvasXpress/assets/254923/2358b5e0-61fc-4f03-b79a-75b8c9e3feb6)

**Comment by TheWildParamecium** [comment]
Thank you so much for your help!

I will stay tuned for the release of the update mentioned beforehand and give you feedback once I try re-executing the reports

**Comment by neuhausi** [comment]
Please check version 50.3 and close

**Comment by TheWildParamecium** [comment]
I recently had the opportunity to relaunch the result report again and can confirm that it is correctly working now.  Thank you so much!
