### ISSUE TITLE
Problems with sample agrupation on circular graphs

### ISSUE THREAD

**Issue by seoanezonjic** [neuhausi/canvasXpress#16]
Sorry neuhasi, I'm using intensively your javascript library and I discover weird things with my data. Using your last version of circular graphs, the sample agrupation with 'smpOverlays' property mix randomly the samples as you can view:
![cx-obj_36_](https://cloud.githubusercontent.com/assets/4126037/22846237/d6f08576-efe6-11e6-87c9-1cfe0f675ee7.png)
![cx-obj_37_](https://cloud.githubusercontent.com/assets/4126037/22846238/d6f2c1f6-efe6-11e6-82b8-f698ca6db28f.png)
 The sample names that is shown on charts contains the conditions used on the experiment (time: 7d -28d and individual names: Rev, wildtype, etc). I build a graph for each factor, the first for time and the last for individual names. If you check the sample names there are mixed samples. For example, in the first chart there is r2_28_Rev1_1 sample in the 7d overlay when it is a 28d sample. In the second chart the overlays are completly mixed and on the bottom of image, in fact, a overlay invades a group of samples.
I've checked th json data and y think that the sample names and sample attributes arrays are correctly related, so I don't know what causes the sample mixing.
Thank you in advance and my apologies for the all the inconveniences.
Pedro

**Comment by neuhausi** [comment]
Fixed in next version. Thank you.

**Comment by neuhausi** [comment]
Please Download Version 14.1
