### ISSUE TITLE
Unexpected problem filtering in heatmap

### ISSUE THREAD

**Issue by federedef** [neuhausi/canvasXpress#160]
Good afternoon,

I have plotted a heatmap and was trying to filter in some samples (Biological Process and Hippie, for example).
Original plot was:
![example](https://github.com/neuhausi/canvasXpress/assets/80126703/5b35cdac-655f-4fed-8537-8774fac226cc)
But filtered by sample plot was:
![example_filtered](https://github.com/neuhausi/canvasXpress/assets/80126703/43ae8375-d11b-4781-896b-cdcac770cf59)

The problem here is that although I only wanted to filter by sample, it seems that there has been a reconfiguration in the table and the labels that appear in the bars above and below have been modified, deleting some of their values.

I was wondering if there is any possible solution to the problem.

Thank you in advance for your time.

**Comment by neuhausi** [comment]
This is very difficult to debug as you have genes with exactly the same gene name. I believe this can be the source of the problem. Can you give unique names to the rows and columns of your dataframe?

**Comment by federedef** [comment]
I just added unique names to the columns for the table and now is working fine. 
Thank you so much and sorry for the inconvenience.

**Comment by federedef** [comment]
Sorry for bothering you again but before closing the issue I have just found another problem when filtering. Now related with the dendogram and the samples clustering.
I started with this heatmap (now with the unique columns corrected)...
![cX-obj_0_ (7)](https://github.com/neuhausi/canvasXpress/assets/80126703/78b3b0f0-d7f8-48be-b442-753167c2af91)
... and now I filter by some samples:
![cX-obj_0_ (8)](https://github.com/neuhausi/canvasXpress/assets/80126703/78093e07-ac7d-4738-bd43-cf3fd26b202f)

...Now the samples clustering is not updated after the filter, not showing correctly a sample aggrupation. Should be that the expected behaviour?

Thanks again in advance.

**Comment by neuhausi** [comment]
I am surprised the  dendrogram didn't disappear as it is supposed to since the structure of the samples (in this case) changed. How did you filter the data from the top heatmap to convert it into the bottom heatmap?

**Comment by neuhausi** [comment]
I remove the sample dendrogram if the samples are filtered and the variable dendrogram if the variables are filtered. I do this automatically in version 50.5

**Comment by neuhausi** [comment]
That won't be possible since you remove samples. I would have to re-cluster every time there is a filter event which would be computationally expensive and will change the order of the samples constantly making it very distracting. I suppose that is a possibility but we should label it as a new feature. I am working in creating LLMs for CanvasXpress so that will have to wait

**Comment by federedef** [comment]
I understand the problematic, in that case removing the sample dendrogram if the samples are filtered is fine.

Thanks for the answer and good luck with the LLMs.
