### ISSUE TITLE
Can the view of a graph be set to how it looks in explore data?

### ISSUE THREAD

**Issue by sarah-binf** [neuhausi/canvasXpress#162]
In the configurations, setting `"view": "layout"` generates the same view as when you click the `explore data`  icon but without the table. Is there a way to get the table to appear by default as well (as seen in the attached image of the dotplot-8 example)? 
![api_general_view](https://github.com/user-attachments/assets/3cf341d2-2ae0-474d-81b4-9692be5c0179)
![dotplot-8_explore_data_view](https://github.com/user-attachments/assets/62741425-59fd-4b3d-a4bc-40b71a73c200)

**Comment by neuhausi** [comment]
Looks like a bug. Oh wait, it is a bug. I will fix in the next version. Thank you

**Comment by sarah-binf** [comment]
Do you know when this might be fixed?

**Comment by neuhausi** [comment]
Once I push version 51.5 next week

**Comment by neuhausi** [comment]
Please check again version 51.5 and close. You need to set the view to 'layout'

**Comment by sarah-binf** [comment]
Thank you!
