### ISSUE TITLE
Is it possible to hide customisation options?

### ISSUE THREAD

**Issue by SunnyMug** [neuhausi/canvasXpress#164]
Hi there! We ran into an issue with our project where when the user selects some of the customisation options for a CanvasXpress, plot, it displays errors since they do not apply to the currently displayed plot type or it distorts the data displayed entirely. To solve this, I was wondering if there is a way to hide some of the customisation option tabs available to the user?

To show you what I mean, the user would first click the customisation option here:
<img width="794" alt="image" src="https://github.com/user-attachments/assets/e59b55b2-a862-43eb-a526-42b04a0d387f">

Clicking the data customisation optiosn tab on the left, if any of the sort functions are clicked, it does not appear to make any changes at all to the plot.
![image](https://github.com/user-attachments/assets/8b2f03cc-e5bd-4d9a-951b-1853574a72de)

Another example is that clicking the options tab, and changing the plot type usually distorts the plot to something that does not make sense, and it is often not reversible unless the plot is reproduced again.
![image](https://github.com/user-attachments/assets/13d9f968-9eec-4c7c-a667-58c9f8a0c88f)

However, there are a few customisation options that we do think will be very useful to the users so  we did not want to hide the customisation page entirely. Is there a way to hide certain options in the customisation page?

For example, In this image, I would like to hide the "Type" choices and keep the "Sample width" choices.
![image](https://github.com/user-attachments/assets/e59555d8-c29f-49b3-b5c5-a5b0521d97e5)

Thank you!

**Comment by neuhausi** [comment]
I would have to implement this in the configuration of the plot. I have done something similar to the data table. That is also a lot of work. BTW clicking on the sorting doesn't work like that. You need to drag the item into the sorting icon. :-)
I will add this as  a feature request
