### ISSUE TITLE
Can't get canvasxpress or canvasxpress-react npm packages to work

### ISSUE THREAD

**Issue by ktaouk1** [neuhausi/canvasXpress#170]
Hi Isaac,
I'm getting issues when installing both the `canvasxpress` and `canvasxpress-react` packages via npm.

This is the code I use (two examples - one for each package. Both gave the same error):
```jsx
// Example 1 - canvasxpress

import * as CanvasXpress from 'canvasxpress';

function App(): JSX.Element {
  // Data
  const data = {
    y: {
      vars: ['Gene1'],
      smps: ['Smp1', 'Smp2', 'Smp3'],
      data: [[10, 35, 88]],
    },
  };

  // Configuration
  const conf = { graphType: 'Bar' };

  // Initialize object
  const cX = new CanvasXpress('graph1', data, conf);

  return (
    <canvas
      id="graph1"
      width={450}
      height={450}
    />
  );
}

export default App;
```

```jsx
// Example 2 - canvasxpress-react

import CanvasXpressReact from 'canvasxpress-react';

function App(): JSX.Element {
  // Data
  const data = {
    y: {
      vars: ['Gene1'],
      smps: ['Smp1', 'Smp2', 'Smp3'],
      data: [[10, 35, 88]],
    },
  };

  // Configuration
  const conf = { graphType: 'Bar' };

  return (
    <CanvasXpressReact
      target="canvas"
      data={data}
      config={conf}
    />
  );
}

export default App;
```

And here's the error I got:
```
✘ [ERROR] Delete of a bare identifier cannot be used with the "esm" output format due to strict mode

    node_modules/canvasxpress/src/canvasXpress.js:16609:23:
      16609 │                 delete t
            ╵                        ^
```

However, I noticed that if I put the code in the `index.html` file directly within a script tag, it works fine:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://www.canvasxpress.org/dist/canvasXpress.css" type="text/css"/>
    <script type="text/javascript" src="https://www.canvasxpress.org/dist/canvasXpress.min.js"></script>
  </head>
  <body>
    <script>
      // Data
      const data = {
        y: {
          vars: ['Gene1'],
          smps: ['Smp1', 'Smp2', 'Smp3'],
          data: [[10, 35, 88]],
        },
      };

      // Configuration
      const conf = { graphType: 'Bar' };

      // Initialize object
      const cX = new CanvasXpress('graph1', data, conf);
    </script>
  </body>
</html>
```

This isn't ideal though, especially since we're using React as part of our tech stack and will need plots in many different components.
I've tried these things so far, with no success:
1. Disabled strict mode
2. Installed and ran with Node `v16.1.0` and `v20.12.2`
3. Removed `node_modules` and cleared cache (`npm cache clear --force`), then fresh installed

I'm assuming this is an issue with `canvasxpress` since it's being used as a dependency for both packages.
Any help would be appreciated, thank you!

**Comment by neuhausi** [comment]
What version? I am happy to work with you to correct the error but I am no expert with react so I will need your help😉

**Comment by ktaouk1** [comment]
No problem, thanks for the quick reply! Here are all the relevant packages and their versions:
```
"react": "^18.2.0",
"react-dom": "^18.2.0",
"canvasxpress": "^51.5.17",
"canvasxpress-react": "^51.5.17",
"vite": "^4.3.9",
```

**Comment by neuhausi** [comment]
The reason is not working is because the  files in the src directory are empty. MY BAD!!! I will create a new version this week

**Comment by neuhausi** [comment]
Can you please check with the new version

**Comment by ktaouk1** [comment]
Hi Isaac, I'm getting this error now:
<img width="506" alt="image" src="https://github.com/user-attachments/assets/3fed6d9c-0fd9-4230-853b-49f72a5b0937">
I've installed both packages, versions here:
```
"canvasxpress": "^51.7.1",
"canvasxpress-react": "^51.7.1",
```

**Comment by neuhausi** [comment]
Any chance you can build  a minimal app I can debug?

**Comment by ktaouk1** [comment]
This should work :)
https://codesandbox.io/p/sandbox/fragrant-hill-pnksyd?file=/src/App.js:12,11

**Comment by neuhausi** [comment]
```
"dependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-scripts": "^5.0.0",
    "canvasxpress-react": "51.7.1"
  },
```
Shouldn't the above code be:
```
"dependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-scripts": "^5.0.0",
    "canvasxpress": "51.7.1",
    "canvasxpress-react": "51.7.1"
  },
```

**Comment by ktaouk1** [comment]
Hi Isaac, sorry looks like I forgot an import (the package list is fine though, since `canvasxpress-react` has `canvasxpress` as a dependency). Seems to be working now, thanks!

**Comment by neuhausi** [comment]
Wow!. What a relief. I didn't know what else to do! Can you please close the issue.
Thank you.

**Comment by neuhausi** [comment]
May I have you name to credit you for the example? I copied your repo and created a link to it in the canvasxpress-react repo

**Comment by ktaouk1** [comment]
Sure thing! Kamile Taouk :)

**Comment by neuhausi** [comment]
https://github.com/neuhausi/canvasxpress-react/blob/master/README.md

From: ktaouk1 ***@***.***>
Date: Tuesday, August 20, 2024 at 4:35 PM
To: neuhausi/canvasXpress ***@***.***>
Cc: Isaac Neuhaus ***@***.***>, Mention ***@***.***>
Subject: Re: [neuhausi/canvasXpress] Can't get canvasxpress or canvasxpress-react npm packages to work (Issue #170)

Sure thing! Kamile Taouk :)
