### ISSUE TITLE
"Uncaught ReferenceError: CanvasXpress is not defined"

### ISSUE THREAD

**Issue by alin-png** [neuhausi/canvasXpress#173]
Might be related to this previous issue [#170](https://github.com/neuhausi/canvasXpress/issues/170 ) where canvasxpress-react does not seem to work via npm. 
Here's an image of the error:
<img width="710" alt="image" src="https://github.com/user-attachments/assets/43216296-25e5-49c2-bd57-7e4ce832ee01">

I've used the same version of the package from the issue which should work

```
    "canvasxpress": "^51.7.1",
    "canvasxpress-react": "^51.7.1",
```
but the issue remains. Any ideas? Thanks

**Comment by alin-png** [comment]
Hi @neuhausi , I've put the following into my index.html

```
<link rel="stylesheet" href="https://www.canvasxpress.org/dist/canvasXpress.css" type="text/css"/>
 <script type="text/javascript" src="https://www.canvasxpress.org/dist/canvasXpress.min.js"></script>
```

and the above error no longer persists, but now I am recieving these errors:
<img width="739" alt="image" src="https://github.com/user-attachments/assets/d8802d56-54d9-4ae2-98dc-12eb8f6f450a">

Does this provide any clues? thanks

**Comment by neuhausi** [comment]
Any chance you can provide me with a minimal example? I can't reproduce it.

**Comment by alin-png** [comment]
Hi @neuhausi , after doing some more investigation my team and I have figured that it's not working with vite because vite requires strict mode which CanvasXpress does not use. Is there any chance that you can turn strict mode on? We'd really love to use CanvasXpress for circos plots as we find other packages don't offer the same features as CanvasXpress. Thanks!

Looping in @ktaouk1 as he is more familiar with our codebase.

**Comment by neuhausi** [comment]
Yes. I will investigate how to enforce strict mode

**Comment by neuhausi** [comment]
I would have to add a strict function inside every function. I need to investigate how to this globally instead. Sorry but I need to push a new version so it will have to wait until the next one.

**Comment by alin-png** [comment]
No worries, appreciate you working on this @neuhausi

**Comment by neuhausi** [comment]
Actually I think I can get it in this ext version. I put a 'use strict' at the begining of the file and I am finding a few variables without scope. I will let you know

**Comment by neuhausi** [comment]
I am going to release version 52.3. I cannot enforced use strict but it should work as I fixed all the instances of variables not defined. I need to figure out how to load Google fonts dynamically under strict mode. Please check it and let me know

**Comment by alin-png** [comment]
Thank you so much @neuhausi !! Just tested it out it seems to be working now!!

**Comment by neuhausi** [comment]
Awesome. Please close the ticket
Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
