### ISSUE TITLE
Interactively clustering samples in heatmap duplicates some of them

### ISSUE THREAD

**Issue by AEstebanMar** [neuhausi/canvasXpress#174]
Hello, I have found an issue when interactively exploring some data I have generated.

When I clusterise a heatmap by sample, some samples are duplicated. It only seems to happen when there is a large amount of them.

Here is an example. Prior to clustering, my heatmap looks like this:

![cX-obj_0_](https://github.com/user-attachments/assets/38578f39-fdb7-4f22-bd99-3ad210606e7a)

But when I right click and select cluster by samples, I get this:

![cX-obj_0_(1)](https://github.com/user-attachments/assets/506da734-e95f-4f37-aec9-c52f5499b0e9)

If you look closely, the row labeled as 1 is duplicated, and each occurrence clusters differently. I have encountered this issue when working with real data and more than one sample can be affected.

Is this a bug, or can each sample end up in multiple clusters at once?

**Comment by neuhausi** [comment]
Yes. That seems to be a bug. Any chance you can add labels to the rows and columns just to check if that fix the error? I need to create a much smaller heatmap to debug.
Thank you

**Comment by neuhausi** [comment]
Please close after you check!

**Comment by AEstebanMar** [comment]
I have checked what you suggested about the data matrix. It only contains one row called 1 before clustering, and then it contains two after clustering (checked by clicking the "View table" button in the interactive plot and sorting the rows). Just in case, I have repeated the example with named rows and columns, simply renaming them in the original data I sent you.
Here is the result before clustering:
![pre_clustering](https://github.com/user-attachments/assets/fc21f731-ad12-4002-8e0f-5064a4781565)

And after clustering:
![post_clustering](https://github.com/user-attachments/assets/a2d45ba1-415e-483e-ad26-0719fd042dcd)

It seems that assigning row names fixes the problem. Could it be that the bug only occurs when row names are numeric?

**Comment by neuhausi** [comment]
Do you have a small dataset

Isaac Neuhaus PhD.

**Comment by AEstebanMar** [comment]
I've repeated it with only four samples, and I've noticed something even more strange.

Before clustering:
![Unlabeled_small_pre_clustering](https://github.com/user-attachments/assets/dfa5d415-69ea-4709-a17d-eaf9e6eb5692)

After clustering:
![unlabeled_small_post_clustering](https://github.com/user-attachments/assets/dd055cb5-ad3c-4c3a-ae86-8e47ffaaec74)

It looks like sample 1 is overwriting sample 4 after clustering. Again, no issue with labeled row names, but adding them too just in case:

Before clustering:
![labeled_small_pre_clustering](https://github.com/user-attachments/assets/b7cd7895-0370-4b36-99aa-5418ba11071b)


After clustering:
![labeled_small_post_clustering](https://github.com/user-attachments/assets/914185fa-ba23-4e65-bd93-aacb3b120492)

**Comment by neuhausi** [comment]
Thank you so much for following up. I will keep in in the TO DO: and KNOWN issues with datasets having only numeric identifiers. I will try to address in the following version.

**Comment by AEstebanMar** [comment]
Thank you for your help. Looking forward to the next update!
