### ISSUE TITLE
Legend shape for violin plots

### ISSUE THREAD

**Issue by alin-png** [neuhausi/canvasXpress#176]
Hi Isaac, 

Hope you have been well. I was wondering if it is possible to change the shape in the legend for violin plots from square to circle? Plus in the examples for violin plots the plot preview image shows circle as the legend:
![image](https://github.com/user-attachments/assets/75e245f9-31f2-4c06-8232-eeca899151d3)

However, clicking into it shows the legend as square:
<img width="901" alt="image" src="https://github.com/user-attachments/assets/5f9cf100-b67e-4d04-b64f-44d8c604aa4f">

I believe it's more intuitive for it to be a circle as the dot points are circle as well. What do you think? thanks :)

**Comment by neuhausi** [comment]
Absolutely. I will convert the legend to circles in the next version

**Comment by neuhausi** [comment]
What about this:
![cX-violin13](https://github.com/user-attachments/assets/af2e2d4e-35c9-4257-9023-c2671046521a)
![cX-violin15](https://github.com/user-attachments/assets/64ed1301-9c9a-4bde-8fc5-29e380745786)
![cX-violin16](https://github.com/user-attachments/assets/baf22898-8c27-44ac-bbcc-2d736d93792c)

**Comment by alin-png** [comment]
@neuhausi Yes, that's perfect! Thanks so much

**Comment by neuhausi** [comment]
Release 53.0. Please check and close issue

From: Angela ***@***.***>
Date: Wednesday, November 20, 2024 at 7:39 PM
To: neuhausi/canvasXpress ***@***.***>
Cc: Isaac Neuhaus ***@***.***>, Mention ***@***.***>
Subject: Re: [neuhausi/canvasXpress] Legend shape for violin plots (Issue #176)

@neuhausi<https://github.com/neuhausi> Yes, that's perfect! Thanks so much
