### ISSUE TITLE
data ->bug

### ISSUE THREAD

**Issue by minzhenyu** [neuhausi/canvasXpress#18]
I use the demo:http://canvasxpress.org/html/bar-7.html,
just change the data  to
	            "y" : {
	              "vars" : ["(0.01,0.1]", "(0.1,0.25]", "(0.25,0.5]", "(0.5,1]", "(1,3]", "(3,10]", "(10,20]", "(20,60]"],
	              "smps" : ["0-10", "10-20", " 20-30", "30-40", "40-50", "50-60", "60-70", "70-80", "80-90"],
	              "data" : [[1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 2], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0]],
	              "desc" : ["Magnitude1", "Magnitude2"]
	            },
but the  chart is  not right, the Z axis is also wrong,how can I get the right chart

**Comment by minzhenyu** [comment]
[3d.zip](https://github.com/neuhausi/canvasXpress/files/810091/3d.zip)
![wechatimg15](https://cloud.githubusercontent.com/assets/12856051/23452520/952550dc-fe9f-11e6-8fb7-63bbdaaaea56.jpeg)

**Comment by neuhausi** [comment]
It is a bug. It didn't like the zeros. I will fix it in the next version.
Regards,
Isaac
![cx-canvas 2](https://cloud.githubusercontent.com/assets/254923/23489116/b0c79966-febe-11e6-9d91-61184b2ca634.png)

**Comment by minzhenyu** [comment]
ok,thanks

**Comment by neuhausi** [comment]
Ok. I fixed it. I also adjusted the width of the bars. I will upload a new version soon. Thank you for reporting the bug.
Isaac
![cx-canvas 3](https://cloud.githubusercontent.com/assets/254923/23491963/97890b54-fecf-11e6-8adb-5f3e26716e48.png)

**Comment by minzhenyu** [comment]
ok,thank you

**Comment by minzhenyu** [comment]
I am sorry, I use my data and download the version 14.6 but the chart is
<img width="531" alt="qq20170303-113228 2x" src="https://cloud.githubusercontent.com/assets/12856051/23537191/66a1efec-0005-11e7-9e7a-73d29032e5e2.png">

**Comment by neuhausi** [comment]
You need to download CanvasXpress from the website if you want to use it outside R.
www.canvasxpress.org
Regards,
Isaac

**Comment by minzhenyu** [comment]
Thanks for your answer,this is my demo, did i set a wrong option?

**Comment by neuhausi** [comment]
Please download new version

**Comment by minzhenyu** [comment]
Thank you very much

**Comment by minzhenyu** [comment]
canvasxpress.org <http://canvasxpress.org/>  this address has something wrong

**Comment by minzhenyu** [comment]
canvasxpress.org <http://canvasxpress.org/>  this address is wrong
