### ISSUE TITLE
Zoom on both axis in 1-D charts

### ISSUE THREAD

**Issue by cb4ds** [neuhausi/canvasXpress#21]
It would be great to be able to zoom based on both axis on 1D charts instead of just the numeric axis.  Would help with visualization of dense categorical data.  It is also intuitive to a user to be able to drag to zoom in both directions.

**Comment by neuhausi** [comment]
You can do that by pressing Shift and dragging your mouse. You will see that the dragging area extend across the X-Axis

**Comment by cb4ds** [comment]
awesome - thanks

**Comment by cb4ds** [comment]
This doesn't seem to work for certain situations.  Attached is an mtcars example where I can't shift-zoom on the categorical axis (y in this case)

![mtcars_ex2](https://cloud.githubusercontent.com/assets/9085025/24061381/78cbeaa0-0b14-11e7-9f5b-7707129cd2f5.png)
[mtcars_ex2.txt](https://github.com/neuhausi/canvasXpress/files/851669/mtcars_ex2.txt)

**Comment by baohongz** [comment]
This is a bug introduced in version 14.9. Version 14.7 is fine.

**Comment by neuhausi** [comment]
The zooming for the X-Axis works only for the variable axis. In your example you have the data across the samples. If you transpose the data then you can use the mouse wheel or Shift + drag to zoom in. I suppose in the future I could add zoom in/out also for the sample axis.
![cx-htmlwidget-42e38ff09777a78c82b1-cx](https://cloud.githubusercontent.com/assets/254923/24081635/066420f6-0c8e-11e7-9f76-d558eadb6684.png)

**Comment by cb4ds** [comment]
Thanks for the work-around, I'll reshape and use the data that way.
