### ISSUE TITLE
SSL cert and HTTPS hosting for http://www.canvasxpress.org/cgi-bin/services.pl

### ISSUE THREAD

**Issue by sammyjava** [neuhausi/canvasXpress#22]
Hiya. I'm running my sites over SSL now, and I get the dreaded yellow "insecure page" icon on pages that use canvasXpress.min.js because it calls http://www.canvasxpress.org/cgi-bin/services.pl.

I'd request that either this be changed to a working HTTPS URL or removed, so that the site shows the pretty green "all secure" icon on these pages. :) THANKS! (There is currently HTTPS serving on that domain, but it's got SSL certs for other sites.)

**Comment by neuhausi** [comment]
Working on it.
Thank you.
Isaac

**Comment by neuhausi** [comment]
Done. Give it a try and let me know if everything is a green light.
:-)

**Comment by sammyjava** [comment]
What did you change? Did you switch to https://www.canvasxpress.org/cgi-bin/services.pl in a new but not yet official version? Did you want me to manually change that to https? I'm using 15.0.

**Comment by sammyjava** [comment]
I did replace http with https throughout canvasXpress.min.js and we're green light!
