### ISSUE TITLE
NaN in tooltips for non-numeric variables

### ISSUE THREAD

**Issue by cb4ds** [neuhausi/canvasXpress#23]
On a scatterplot I'm seeing NaN when I include the var in the main data so that it shows on the tooltip.

[mtcars_example.pdf](https://github.com/neuhausi/canvasXpress/files/851308/mtcars_example.pdf)
[R and JSON.zip](https://github.com/neuhausi/canvasXpress/files/851309/R.and.JSON.zip)

**Comment by cb4ds** [comment]
Here is the file saved with RR turned on.

![mtcars_example](https://cloud.githubusercontent.com/assets/9085025/24055720/6ac5b0dc-0afe-11e7-8436-58d5bec44077.png)

**Comment by neuhausi** [comment]
Is the problem that the value for gear is 'null' and is displaying NaN?

**Comment by cb4ds** [comment]
Yes, in the tooltip hover over the points.

**Comment by neuhausi** [comment]
Fixed in new version (15.0)
