### ISSUE TITLE
Color scheme issue with heatmaps

### ISSUE THREAD

**Issue by seoanezonjic** [neuhausi/canvasXpress#24]
Hi neuhasi
I'm working with heatmap  and I have a problem when I'm setting the color scheme. IMy data have extreme values as 0 and 100. I want to show them as dark blue and dark red, but the 100 value never gets dark red. I'm trying several configurations with the properties:
- colorSpectrumBreaks
- colorSpectrum
- colorSpectrumNumber

But the color scheme seems to skip the last colors in the red scale zone. What I'm doing wrong?
![cx-obj_0_](https://cloud.githubusercontent.com/assets/4126037/24099509/04fca660-0d70-11e7-926c-b9960925deb3.png)
Thanks in advance

**Comment by neuhausi** [comment]
You change the algorithm to calculate the range of the data. The default is 'heckbert'. I changed it in this graph to 'rPretty' (that is the default in R but you can use also 'wilkinson'). 
The parameter name is 
...
axisAlgorithm: 'rPretty'
...

You can also set the range to whatever value you want. The parameter for that is:
...
 setMaxX : 100
...
But I prefer the first method.
Regards,
Isaac
![cx-canvas 8](https://cloud.githubusercontent.com/assets/254923/24110991/686338cc-0d6b-11e7-8015-7992e0f6e687.png)
