### ISSUE TITLE
Questions about heatmaps in CanvasXpress

### ISSUE THREAD

**Issue by Louis-Berlic** [neuhausi/canvasXpress#26]
Hello,

I have some questions about CanvasXpress heatmaps:
 
- Is there a way to reverse the heatmap graph (put the variables on the left and the samples at the bottom) by program without using the transpose() function?
- Is there a way to highlight variables by program using their name or index? In fact I would like to higlight an entire part of a cluster.
- Is it possible that when highliging a variable, the corresponding leaf in the dendrogram turns red like the label does?

If those features are not implemented yet, could you please consider including them to the next update? 

Thank you.

Louis.

**Comment by neuhausi** [comment]
_Is there a way to reverse the heatmap graph (put the variables on the left and the samples at the bottom) by program without using the transpose() function?_

- **Not at this time. Why wouldn't you want to use transpose or transpose the data before?**

_Is there a way to highlight variables by program using their name or index? In fact I would like to higlight an entire part of a cluster._

- **This is already posible with highlightSmp and highlightVar. See this [*example*](http://canvasxpress.org/html/heatmap-8.html).**

_Is it possible that when highliging a variable, the corresponding leaf in the dendrogram turns red like the label does?_

- **Not at this time but I can add this in the next version**

**Comment by Louis-Berlic** [comment]
Thank you for your answers.

*Why wouldn't you want to use transpose or transpose the data before?*
- **You're right, I could transpose the data before, I don't remember why I didn't want to do it but it works now.**

*This is already posible with highlightSmp and highlightVar.*
- **I know about this option but what I want to do is dynamically highliting samples when I click a button somewhere else on the page. The expected result is the same as when you highlight variables from *Menu > Customize > Variable labels > Highlight > Variables > VariableName*. Or is it possible to change by program the configuration object to include highlightSmp and reload the heatmap with the new configuration?**

*Not at this time but I can add this in the next version*
- **I would really appreciate it if you did, thank you in advance.**

**Comment by neuhausi** [comment]
Regarding highlighting:
You can get the CanvasXpress object grammatically, then modify the property and then draw again. 
Something like this:

`var cX = CanvasXpress.$(targetId);` // Where targetId is the DOM id for the canvas element
`cX.highlightSmp = ['Sample1', 'Sample2'];` // The samples you want to highlight
`cX.draw();` // Redraw the canvas

In general you can always use this method to modify any property in CanvasXpress.

Regarding the coloring of the dendrograms:
Done in version 15.5. (I will upload soon). I also added a method to color the variable and sample dendrograms by any annotation given in the data. Here are a couple of examples:

Here is the default when you highlight samples or variables:

![cx-heatmap8](https://cloud.githubusercontent.com/assets/254923/25314447/0e7c73de-2812-11e7-8108-fecf21695991.png)

And here is an example where you color by an annotation. (In this example I am coloring by 'Treatment').

`colorSmpDendrogramBy: 'Treatment`

![cx-heatmap8 1](https://cloud.githubusercontent.com/assets/254923/25314464/56228fc0-2812-11e7-8bc7-192149d5c9fe.png)

**Comment by Louis-Berlic** [comment]
That's great, thank you very much!
