### ISSUE TITLE
Changing the source data of heatmap

### ISSUE THREAD

**Issue by Louis-Berlic** [neuhausi/canvasXpress#27]
Hello neuhausi,

In your last answer you (issue 26), you said I could modify any property of the graph and then redraw it using `cX.draw()`. Can I use a similar method to change the source data of the heatmap? I used to remove all the elements from the DOM and create a new heatmap but after your last answer I tried the following:

`cX.data = data; // my json data obect`
`cX.draw();`

This works perfectly when the size of the dataset is the same size as the previous dataset but when It is bigger or smaller, it causes problems (with `smpIndices` and `varIndices` I guess).

Is there a method allowing to change the source data, or do you recommand another way of doing it?

Thank you in advance.

**Comment by neuhausi** [comment]
I meant property that you pass in the config/ the cx.data is an object. you need to use cx.updateData(data) instead.
Sorry for the confusion.
Isaac

**Comment by Louis-Berlic** [comment]
Thank you a lot, it works.

Sorry I'm kind of "reopening" this issue but this is closely related to my previous question.

There is just an annoying detail: the scale (gradient of colors) does not update. For example if I `changeData()` with new data ranging from 0 to 300 and previous data ranged from 0 to 3000, the max value remains at 3000 and all my 0 - 300 data is considered to be "small" values.

Is there another function to update the heatmap indicator, or another way to resolve the problem? And is there a documentation for *functions*? Thank you in advance.
