### ISSUE TITLE
Heatmap error when hiding variables dendrogram

### ISSUE THREAD

**Issue by Louis-Berlic** [neuhausi/canvasXpress#29]
Hello,

I ran into a problem when a wanted to implement a checkbox that shows/hides variables dendrogram.

When I call the function `showHideDendrogram("showVarDendrogram")`, I get an error in a dialog box and both sample and variable dendrograms disapear.

You can reproduce this error on any example from the doc (like [this one](http://canvasxpress.org/html/heatmap-8.html)) by clicking Clusters -> Hide dendrogram (the variables one) in the "right-click menu".

I looked a bit at the code (version 15.5) and I think I located the problem, maybe it can help:

In function parseNewick, you check if we are dealing with variables like this:

`if(e == "varDendrogram" && this.showVarDendrogram) {`

and if not (else statement), you assume that we are dealing with samples, but in this case it is only the second condition (`this.showVarDendrogram`) that is false. So a bit further in the code, when you check this:

`if(this[e].nodes.length != this.data.y.smps.length) {`

in this particular case you are actually checking variables nodes length against smps length.

**Comment by neuhausi** [comment]
oh Yes. That should happen. I will look into it.
Thank you.
Isaac

**Comment by neuhausi** [comment]
Fixed. It will be released in the next version.
Thank you.
Isaac

**Comment by Louis-Berlic** [comment]
Thank you!

**Comment by Louis-Berlic** [comment]
I can't see the fix in version 15.6, is it normal? I just added a `if(e == "smpDendrogram") {...}` condition in my current version for now.

**Comment by neuhausi** [comment]
It will be there in the next version (15.7)

**Comment by neuhausi** [comment]
Version 15.7 is out. Please verify it is fixed.

**Comment by Louis-Berlic** [comment]
Sorry I was a bit impatient, it is fixed in 15.8. Thank you.
