### ISSUE TITLE
Bug: Overlay Label is cut short after "Transpose"

### ISSUE THREAD

**Issue by baohongz** [neuhausi/canvasXpress#32]
http://canvasxpress.org/html/heatmap-8.html

After "Transpose" the above plot, "Treatment" label becomes "Treatme". The whole label will show up by zooming in on the heatmap.

**Comment by neuhausi** [comment]
Fixed in Version 15.9

**Comment by baohongz** [comment]
Are you going to update the canvasXpress.org web site soon? It is still version 15.8.

Thanks,
Baohong
