### ISSUE TITLE
Does canvasXpress provide a nice popup alternative to alert()?

### ISSUE THREAD

**Issue by sammyjava** [neuhausi/canvasXpress#43]
Just wondering if there's a nice popup function within canvasXpress that I can use in my click:function(o) calls. If not, do you recommend something that's nice? I'm currently using alert() which is fairly bush league. Thanks!

**Comment by neuhausi** [comment]
Have you seen showInfoSpan?
<pre>

var data = {
  "y": {
    "vars": ["Gene1"],
    "smps": ["Smp1", "Smp2", "Smp3"],
    "data": [[10, 35, 88]]
  }
};
                   
var conf = {
  "graphType": "Bar"
};
                   
var evts = {
  "mousemove" : function(o, e, t) {
    t.showInfoSpan(e, "&lt;pre>" + t.prettyJSON(o) + "&lt;/pre>");
  },
  "mouseout" : function(o, e, t) {    
  },
  "click" : function(o, e, t) {
    var s = "click on var " + o.y.vars[0] + " and smp " + o.y.smps[0];
    t.showInfoSpan(e, s);
  },
  "dblclick" : function(o, e, t) {
    var s = "dblclick on var " + o.y.vars[0] + " and smp " + o.y.smps[0];
    t.showInfoSpan(e, s);
  }
};
                        
var cX = new CanvasXpress("canvasId", data, conf, evts);

</pre>

**Comment by sammyjava** [comment]
PERFECT! Thanks!!!
