### ISSUE TITLE
How to integrate canvasXpress with angular 2 typescript application

### ISSUE THREAD

**Issue by tonytomk** [neuhausi/canvasXpress#5]
Hi Team,

Is it possible to integrate canvasXpress with angular 2 typescript applications.
need help on this, thanks in advance :)

**Comment by MatthewRalston** [comment]
Hi @tonytomk, in principle it should be able to integrate with nearly any clientside application. The configuration is JSON so you should be able to generate a config object programatically and load the canvas. That said, we'd need to better understand your use case. 

* Where is the data? 
* Is the typescript portion relevant to your usecase, as I'm assuming that's on the server side?
* If I might rephrase your question, you are looking for functionality within canvasXpress to either:
  * load data directly into your config through some API route
  * load data from some DOM component (e.g. a table)

 As far as I know, most graphics libraries (d3, threejs, etc. ) start with the developer providing JSON format data to a function (in this case canvasXpress). This could be less convenient if the data is dynamic, and an update/Ajax polling routine could be useful...

**Comment by baohongz** [comment]
Please read the paper and also download the source to see how the canvasXpress is integrated into an client application.

http://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-015-2356-9

An example,

http://baohongz.github.io/QuickRNASeq/

Best,
Baohong

**Comment by urvashimehra** [comment]
I am facing same issue. Please Help...

**Comment by urvashimehra** [comment]
i have angular app and wanted to draw canvasXpress chart on my component but unable to implement that code... if i am copying and paste html code on idex page it is working fine but when i am installing and trying to draw chart on my component it is giving error

**Comment by neuhausi** [comment]
Can you please share the error?

**Comment by urvashimehra** [comment]
it was giving 'agrgument can't be null'
i resolved this error by adding script in component............
thanks a lot for reply.......... :)

**Comment by neuhausi** [comment]
Sorry but you need to post the whole code for me to be able to help you since I am not familiar with Angular that much.

**Comment by urvashimehra** [comment]
![image](https://user-images.githubusercontent.com/8348675/116969475-f1382e80-acd3-11eb-8135-ab2daf125232.png)

**Comment by neuhausi** [comment]
This looks like a problem with the data. Can you share the data?

**Comment by urvashimehra** [comment]
can you share steps how to implement  canvasXpress manhattan plot with json data in angular 8?

**Comment by urvashimehra** [comment]
![image](https://user-images.githubusercontent.com/8348675/117008389-4aba5080-ad08-11eb-8b7c-d2e54a3e3035.png)

**Comment by neuhausi** [comment]
I see that error when the id of the target is not correct. What is the target id for the canvas?
