### ISSUE TITLE
Extend tooltip with additional values in 3D scatter plot

### ISSUE THREAD

**Issue by mmuejde** [neuhausi/canvasXpress#51]
I would like to extend the tooltip in 3D scatterplot(Name, x, y, z, additional values...) with additional values.

**Comment by neuhausi** [comment]
Please look at the documentation:
https://canvasxpress.org/html/documentation.html#events

You just need to add a 4th parameter when you create the CanvasXpress object. Here if some pseudo code:

```
var evt = {
    "mousemove" : function(o, e, t) {
        t.showInfoSpan(e, "<pre>" + t.prettyJSON(o) + "</pre>");
    },
    "mouseout" : function(o, e, t) {      
    }
}
var cX = new CanvasXpress("canvasId", data, config, evt);
```
You can actually copy this event (evt) and try it in your code. The parameters are o (the object that contains the data, e (the actual event) and t (a handle to the canvasXpress object). You can use the chrome developing tools and put a break inside the mousemove function. It is important to leave the mouseout function empty.

Please let me know how it goes!

Isaac

**Comment by mmuejde** [comment]
Thanks, i will try it.
