### ISSUE TITLE
Several problems

### ISSUE THREAD

**Issue by seoanezonjic** [neuhausi/canvasXpress#55]
Hi neuhasi
I working with your js library (the last version, 19.1) and I found the following issues:

-  There is a minor problem with the freegeoip query. It warns the following: `{"__deprecation_message__":"This API endpoint is deprecated and will stop working on July 1st, 2018. For more information please visit: https://github.com/apilayer/freegeoip#readme","ip":"...`
- When I try to export the svg image, the Mozilla browser does nothing and I get the following error in the browser console:
`TypeError: w.indexOf is not a function`
- Using circular graphs, the showRingLegend attribute seems not work and I guess that is set to true by default. I attach an example in which I expect that the variables names are shown in the graph but they not appears (BTW: It is posible to show them in a box out of the circular graph?

![cx-obj_29_](https://user-images.githubusercontent.com/4126037/40107024-c128935e-58e6-11e8-8e0c-b634a9fa7ab7.png)

Thanks in advance by your attention and I want to congratulate you by this great tool.

PD:  I'm using your library in a scientific work and I would like cite you. Can you give me a valid reference?

**Comment by neuhausi** [comment]
First of all, sorry to take this long. The first point is deprecated. I use a different service now. Second point is fixed in version 21.7 and the third point it was an oversight of leaving that parameter in the configuration. You are right, it doesn't work because that parameter is deprecated.
Thank you.
Isaac
