### ISSUE TITLE
Website throwing 404 on download.html (and other internal pages)

### ISSUE THREAD

**Issue by sammyjava** [neuhausi/canvasXpress#56]
I presume we still get the production canvasXpress from the website? All of the internal pages are 404ing right now.

**Comment by neuhausi** [comment]
Sam,
Could you please verify you do not get a 404 anymore?
Thank you.
Isaac

**Comment by sammyjava** [comment]
Still getting a 404 on http://www.canvasxpress.org/download.html

**Comment by neuhausi** [comment]
Can you try this link:
https://www.canvasxpress.org/download.html?123456

**Comment by neuhausi** [comment]
I just noticed your link is not correct it should be:

https://canvasxpress.org/html/download.html

I guess it could be my fault.

Thank you.

Isaac

**Comment by neuhausi** [comment]
Ok. It was a problem on my end. Please go here first:

1. https://canvasxpress.org/index.html which should redirect you to:
https://canvasxpress.org/html/index.html
2. Then click on the download page.

My bad.

Sorry

Isaac

**Comment by sammyjava** [comment]
OK the page is there, but does the download emailer work? I'm not getting a link in my email. (I know it's always the same link, or used to be, but consider me a tester.)

**Comment by sammyjava** [comment]
Still no email. And the page responds really fast, not like it's running a script in response to the post.

**Comment by neuhausi** [comment]
Can you please try one more time again.
I believe this time I fixed it.
Sorry about it.
Isaac

**Comment by sammyjava** [comment]
Yup! Thanks!
