### ISSUE TITLE
Rendering is hanging up on call to canvasxpress.org

### ISSUE THREAD

**Issue by sammyjava** [neuhausi/canvasXpress#58]
We've had some heatmaps hang up on calls like this:
```
https://canvasxpress.org/cgi-bin/services.pl?beacon=MTUzNDM0MjUwNTg0Njo6MTI1MTgyNjYxMTYyMjA3MTo6MjAuMTo6aHR0cHM6Ly9taW5lcy5sZWd1bWVpbmZvLm9yZy9sZWd1bWVtaW5lL2JhZ0RldGFpbHMuZG8/YmFnTmFtZT1HZW5lK2xpc3QrZm9yK2FsbCtvcmdhbmlzbXMrMTUrQXVnKzIwMTgrOC4xNCZ0cmFja0V4ZWN1dGlvbj1mYWxzZQ==
```
Is it necessary to make a call back to `canvasxpress.org/cgi-bin/services.pl`??? This adds an unknown and perhaps unreliable element to our web app. I thought that canvasXpress was a standalone Javascript app.

**Comment by neuhausi** [comment]
I am surprised it hangs. It should return immediately. It is just a one
pixel image.
Isaac

**Comment by sammyjava** [comment]
Is it necessary? Or is it just for logging purposes? Can I remove it?

**Comment by sammyjava** [comment]
I'll close this, it was a result of spitting out a whole bunch of canvasXpress objects in a row, which, I think, hit against a hit-rate limiter on your server. But I'm trying to make a dynamic switcher now, new issue....
