### ISSUE TITLE
Trying to dynamically switch the canvasXpress object's data (heat map)

### ISSUE THREAD

**Issue by sammyjava** [neuhausi/canvasXpress#60]
I've got a stack of heat maps (with JSON data stored in an array) and I'd like to show one at a time with a selector to toggle them. Ideally there'd be a function I can access to update the CanvasXpress instance data (the config and events don't change); not seeing that, I've tried various combinations of deletion / instantiation, none of which render a new heat map on the canvas. Here's the code I'm working with so you can get an idea of what I'm up to.

The **first** time `setExpressionSet` is called, the canvas is rendered correctly.  Subsequent calls fail to replace the canvas with the new heat map. If I don't destroy the instance, I get a spinner with no canvas update (and the browser complains about a stuck script); if I destroy the instance, the canvas is left blank.
```
var conf = config block, works fine
var evts = event handlers, works fine
var cx = null; // we use cx outside the below function, works fine

 // refresh the heatmap with the indicated expression set
 function setExpressionSet(index) {
     // grab the source metadata and expression data
     var sourceJSON = sourcesJSON[index];
     var data = expressionJSON[index];
     // destroy the current heat map
     // CanvasXpress.destroy("canvasx"); ... this didn't work, so I tried:
     if (cx!=null) {
         cx.destroy(); // this also didn't help
     }
     // instantiate the new heat map - this only works on the first call
     cx = new CanvasXpress("canvasx", data, conf, evts);
 }
```

**Comment by sammyjava** [comment]
Oh, I forgot to mention, the browser console throws these errors when I try to create the new CanvasXpress:
```
TypeError: G is null[Learn More] canvasXpress.min.js:471:624283
TypeError: j.resetTooltipDivs is not a function[Learn More] canvasXpress.min.js:471:1098109
```

**Comment by neuhausi** [comment]
Is there a page I can check out?
Why do you want to destroy the canvas? It would be easier and faster to
just update the data. cx.updateData(data);
Regards,
Isaac

**Comment by sammyjava** [comment]
Erm, because that didn't work the first time I tried it -- but now it is working. :) So, closing this ticket! :)

**Comment by neuhausi** [comment]
Ok. Is it possible for me to see the web page or is it protected?
Isaac

**Comment by sammyjava** [comment]
FYI this is in production now:
https://mines.legumeinfo.org/legumemine/bagDetails.do?scope=all&bagName=Photosystem+I+genes
Scroll down past the data table to see the heat map selector.
