### ISSUE TITLE
Violin plots don't align with data points

### ISSUE THREAD

**Issue by baohongz** [neuhausi/canvasXpress#63]
![bug_in_violin](https://user-images.githubusercontent.com/15882624/46839773-8b8a9c80-cd8d-11e8-890c-d673ba27f1c6.jpg)

[cX-plotSection.json.txt](https://github.com/neuhausi/canvasXpress/files/2471065/cX-plotSection.json.txt)

**Comment by neuhausi** [comment]
Fixed in Version 21.7

![cx-plotsection 1](https://user-images.githubusercontent.com/254923/48677161-8c59df80-eb3e-11e8-9127-2b58e5e8dfa4.png)
