### ISSUE TITLE
Numbers don't change on color indicator after log2 data transformation

### ISSUE THREAD

**Issue by baohongz** [neuhausi/canvasXpress#64]
Please perform log2 transformation on this plot and you will observe the bug,

https://canvasxpress.org/html/heatmap-10.html

**Comment by neuhausi** [comment]
There were two bugs. The Color indicator was getting the title of the outline and the color of the data was wrong. This is fixed in version 21.7.

![cx-canvas](https://user-images.githubusercontent.com/254923/48680390-04d59600-eb69-11e8-9f35-aec992e5b156.png)
