### ISSUE TITLE
Does canvasXpress has valid git tag ?

### ISSUE THREAD

**Issue by extend1994** [neuhausi/canvasXpress#8]
Hi,
according to [library request](https://github.com/cdnjs/cdnjs/issues/9334) in cdnjs, I would like to check whether there is a [valid tag](https://github.com/neuhausi/canvasXpress/tags) allowing me to add the library with auto-update config which cdnjs will automatically updates libraries that are known to git repo.
For more details about auto-update config on cdnjs, please click [this](https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md).
For more details about tag, maybe you can check https://git-scm.com/book/en/v2/Git-Basics-Tagging

Thank you!

**Comment by neuhausi** [comment]
Hi I just added a tag to identify the version.
Regards,
Isaac

**Comment by PeterDaveHello** [comment]
Hi Isaac,

Is there a chance to add the tags for other versions? So that we can host them all, thanks!

Best,
Peter

**Comment by neuhausi** [comment]
I will start adding tags to all releases from now on. I won't be able to do
it for the old releases.
Thank you.
isaac

**Comment by PeterDaveHello** [comment]
Thanks @neuhausi
