### ISSUE TITLE
line graphs: horizontal line segments missing

### ISSUE THREAD

**Issue by wmnwmn** [neuhausi/canvasXpress#80]
An example, which had been working earlier in the past year...it is a stepping graph, so all of its lines are entirely vertical or horizontal. Only the vertical lines are being drawn. 

This example also shows a different issue, namely small lines overtop the labels on the horizontal axis. This also was not like this earlier in the past year (with no changes to my code base, so I assume the changes is in CanvasXpress). Also the horizontal labels are being drawn bold faced, which seems wrong because I didn't specify that anywhere. 

![cx-canvasid 1](https://user-images.githubusercontent.com/1850914/53905244-464d5c80-4005-11e9-8670-37986ba51bea.png)

**Comment by neuhausi** [comment]
My Bad! It will be fixed in next version. I implemented a performance routine to avoid drawing lines less < 0.1 px and didn't consider this case.
BTW, You know you can do KM plot in a much simpler way that this right?

**Comment by neuhausi** [comment]
This should be fixed in the current version 23.5
Thank you for reporting that issue.
