### ISSUE TITLE
Boxplots sometimes don't display properly

### ISSUE THREAD

**Issue by JulianDekker** [neuhausi/canvasXpress#81]
Sometimes some parts of the boxplots are hidden, to use https://canvasxpress.org/html/boxplot-1.html as example. I changed group sample to order and got this as result: 
![image](https://user-images.githubusercontent.com/14276117/54532179-7393f600-4987-11e9-8cb6-8eae68205f40.png)

It will display properly when you mouseover over it.

**Comment by neuhausi** [comment]
Cannot reproduce. Could you please verify.
Thank you.

![cX-boxplot1](https://user-images.githubusercontent.com/254923/55524713-3fddef00-565c-11e9-99d8-d2b8d6efdbc5.png)
