### ISSUE TITLE
Pressing the view table button in top menu crashes the plot. 

### ISSUE THREAD

**Issue by JulianDekker** [neuhausi/canvasXpress#82]
pressing the view table button crashes the plot. 
![image](https://user-images.githubusercontent.com/14276117/54532505-2fedbc00-4988-11e9-9ad7-f5dedd383785.png)

![image](https://user-images.githubusercontent.com/14276117/54532470-1ba9bf00-4988-11e9-9991-8c573a961c80.png)

I had this issue on viewing boxplots, it is replicatable using the reference boxplot: https://canvasxpress.org/html/boxplot-1.html

**Comment by fmjabato** [comment]
It also happens using other buttons like "Configure" and launch this error on console when click:
![image](https://user-images.githubusercontent.com/3104434/54605907-a81cb600-4a4a-11e9-83fe-55f37c05309a.png)

**Comment by neuhausi** [comment]
Wow!. I broke it. Will be fixed in the next version!

**Comment by neuhausi** [comment]
Fixed in Version 23.6. Thank you for reporting it!
