### ISSUE TITLE
Data explore scrollbar

### ISSUE THREAD

**Issue by fmjabato** [neuhausi/canvasXpress#83]
I've just updated with the latest version (6 days ago) and I found that there is not a scrollbar when I access to "Explore Data" or "View Table" views.

![image](https://user-images.githubusercontent.com/3104434/55949096-22a7b280-5c52-11e9-828f-f3e0ff40f79c.png)

P.S: thank you for you're excellent work and your fast issues fixing attitude

**Comment by neuhausi** [comment]
I can't reproduce the behavior. The graphs in the examples in the web site show the scroller. Could you please post your data?
Thank you.

**Comment by neuhausi** [comment]
This has been fixed. Otherwise please re-open
