### ISSUE TITLE
Plot crashes when dataset has a completely empty column

### ISSUE THREAD

**Issue by JulianDekker** [neuhausi/canvasXpress#84]
Hi,

Thanks for your work on this library.

The plots seem to crash the page when I try to load in a data set that contains a completely empty row. 

I'm trying to create an CanvasXpress object with these settings:
y:
![image](https://user-images.githubusercontent.com/14276117/56133043-cfa06900-5f8b-11e9-9f3e-87ff689e5b53.png)

x: (My program automatically adds the "No group" row to be able to group all samples together. This shouldn't affect the bug)
![image](https://user-images.githubusercontent.com/14276117/56132990-af70aa00-5f8b-11e9-8836-e8c8a5fdf359.png)

z:
null

styling:
![image](https://user-images.githubusercontent.com/14276117/56133122-fced1700-5f8b-11e9-9d00-20427090e064.png)

new CanvasXpress("canvas", {
      y: yobj,
      x: xobj,
      z: zobj
    }, styling, false);

I cannot share the data I am using so I made a dummy set that reproduces the problem. 

It should be reproducible with this dataset:
https://pastebin.com/05NRK5DV

Let me know if you are unable to reproduce or need additional information.

Thanks

**Comment by neuhausi** [comment]
What version? I downloaded the data set from the link above, converted the semi colons into tabs and drag the file to a canvasXpress gram and here is what I get.

![cX-dummydataset-2nominal3numerical2empty](https://user-images.githubusercontent.com/254923/56547124-6e0f6a00-654a-11e9-8a12-ae67bb26cfeb.png)

**Comment by JulianDekker** [comment]
Version 23.6 but I also had this on 23.5. I will try to reproduce it in a stand-alone version and link that. 

I'm not sure how the drag and drop works I see it generated a scatter. I was trying to make a boxplot maybe it's related to that?

I was testing this in my own environment where I read a file in python, convert it to json and send it to the browser. Then restructure it to fit a format that can be displayed in canvasXpress. 

As I tried debugging this issue I see everything should work as intended. Everything runs and the browser only crashes when it get's to the part where canvasXpress tries to make sense of the data.

I will get back to you with a more complete example of this issue.

**Comment by JulianDekker** [comment]
Okay, to come back to this. I made a version using only HTML and Javascript and it reproduces the issue. 

When I change fill the values in the column it does work but when it's completely null it fails to load. 

You can find my page here:
https://codesandbox.io/embed/733plv9xw6

I left out the canvasXpress files because they would crash codesandbox but import those and you should be able to reproduce the issue.

**Comment by neuhausi** [comment]
My Bad! It will be fixed in 23.7. Thank you.

**Comment by neuhausi** [comment]
Ok. Fixed in Version 23.7. I will upload the new version soon.
![true](https://user-images.githubusercontent.com/254923/56626150-8052dc00-660e-11e9-9e31-3631028cfefb.png)
