### ISSUE TITLE
Can't change font size in correlation plot and black border lines dominate if lots of features are plotted

### ISSUE THREAD

**Issue by baohongz** [neuhausi/canvasXpress#88]
<img width="611" alt="Screen Shot 2019-08-21 at 12 43 35 AM" src="https://user-images.githubusercontent.com/15882624/63403432-39eb6f00-c3ad-11e9-8460-6ca57d048d83.png">

[cX-canvas_Corr.json.txt](https://github.com/neuhausi/canvasXpress/files/3523583/cX-canvas_Corr.json.txt)

**Comment by neuhausi** [comment]
It will be fixed in version 29.7. Sorry for the delay!

**Comment by neuhausi** [comment]
Preview.
Added the following to the config:
    "correlationLabelInterval": 3,
    "varLabelScaleFontFactor": 0.5

![download](https://user-images.githubusercontent.com/254923/94564674-425fdb80-0236-11eb-925e-031e9317dce2.png)
