### ISSUE TITLE
Applying "layoutTopology" in "Search Parameters" doesn't work 

### ISSUE THREAD

**Issue by baohongz** [neuhausi/canvasXpress#91]
I tries to change from "2x2" to "1x3", but nothing happened. Saved JSON file after applying the change becomes invalid. Attached please find original JSON file before the change and screenshot about the change.
<img width="617" alt="Screen Shot 2020-02-18 at 8 28 36 PM" src="https://user-images.githubusercontent.com/15882624/74793323-facfa500-528d-11ea-977f-60818c4c42f1.png">
[test1.json.txt](https://github.com/neuhausi/canvasXpress/files/4222678/test1.json.txt)

**Comment by neuhausi** [comment]
Will be fixed in Version 27.1

**Comment by neuhausi** [comment]
Please try again.
Thank you.
Isaac
