### ISSUE TITLE
Circular Chart does appear in RStudio

### ISSUE THREAD

**Issue by chriswoh** [neuhausi/canvasXpress#95]
I tried to reproduce https://canvasxpress.org/examples/circular-1.html#  using RStudio (v3.5.0, v3.6.1 & v3.6.2) but the plot does not appear/is loading forever. Reproducing a simple venn diagram (https://canvasxpress.org/examples/venn-1.html) works fine.

If I knit the markdown the following error appears:
Could not fetch http://canvasxpress.org/images/uploadFile.jpg
HttpExceptionRequest Request {
  host                 = "canvasxpress.org"
  port                 = 80
  secure               = False
  requestHeaders       = []
  path                 = "/images/uploadFile.jpg"
  queryString          = ""
  method               = "GET"
  proxy                = Just (Proxy {proxyHost = "appaccess-zscaler.boehringer.com", proxyPort = 80})
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 ResponseTimeout

**Comment by cb4ds** [comment]
There is an error in the example code on the website, c() need to be changed to list() - we will resolve this in the next release.  Here is the code for the canvasXpress call in that example, apologies for any inconvenience:

`
canvasXpress(
    data = data,
    smpAnnot = datx,
    varAnnot = datz,
    connections = list(
        list("rgb(255,0,0)","s1","s15"),
        list("rgb(0,255,0)","s25","s120"),
        list("rgb(255,0,0)","s34","s2"),
        list("rgb(255,0,0)","s47","s69"),
        list("rgb(255,0,0)","s15","s74"),
        list("rgb(0,120,0)","s57","s87"),
        list("rgb(255,34,0)","s54","s118"),
        list("rgb(255,0,100)","s78","s18"),
        list("rgb(255,134,0)","s90","s48"),
        list("rgb(120,0,0)","s120","s68"),
        list("rgb(255,0,0)","s131","s92"),
        list("rgb(0,255,0)","s148","s119"),
        list("rgb(0,0,255)","s10","s14"),
        list("rgb(255,0,0)","s56","s6"),
        list("rgb(255,0,0)","s98","s90"),
        list("rgb(255,0,0)","s113","s20")
    ),
    graphType = "Circular",
    ringGraphType = list("dot","heatmap","bar"),
    ringGraphWeight = list(0.5,0.25,0.25),
    segregateSamplesBy = list("Species"),
    segregateVariablesBy = list("Ring"),
    showTransition = FALSE,
    smpOverlays = list("Species"),
    title = "Iris flower data set (1D Circular Plot)",
    transitionStep = 50,
    transitionTime = 1500
)`
