### ISSUE TITLE
help with ## setrlimit: Function not implemented

### ISSUE THREAD

**Issue by bitcometz** [neuhausi/canvasXpress#97]
Hello,

I use udocker to install a container, which including R.
I have used R to generate plot.html with the 'rmarkdown' package.
However, when I change the 'plot' part of the R code in *.Rmd in to the following (an example from your website):

```{r}
library(webshot)
library(canvasXpress)

y <- read.table("http://www.canvasxpress.org/data/cX-irist-dat.txt", header=TRUE, sep="\t",
                quote="", row.names=1, fill=TRUE, check.names=FALSE, stringsAsFactors=FALSE)
z <- read.table("http://www.canvasxpress.org/data/cX-irist-var.txt", header=TRUE, sep= "\t",
                quote="", row.names=1, fill=TRUE, check.names=FALSE, stringsAsFactors=FALSE)
canvasXpress(data      = y,
             varAnnot  = z,
             graphType ="Scatter3D",
             colorBy   = "Species",
             ellipseBy = "Species",
             xAxis     = list("Sepal.Length"),
             yAxis     = list("Petal.Width"),
             zAxis     = list("Petal.Length"),
             theme     = "CanvasXpress",
             title     = "Iris Data Set",
             axisTickScaleFontFactor  = 0.5,
             axisTitleScaleFontFactor = 0.5)
```

The an error is reported :

**## setrlimit: Function not implemented**
## Error in (function (url = NULL, file = "webshot.png", vwidth = 992, vheight = 744, : webshot.js returned failure value: 1

Could you help with me this problem? Thanks !!!!

**Comment by cb4ds** [comment]
This seems like a webshot or other issue in your RMD file and setup.  We are not using webshot in the package and - I am able to run the code above without issue in R 3.5.3, 3.6.3, and 4.0.0.  

_Note:_ I answered your other question on how to save the canvasXpress plot as an html file.  This is generally the first step in using webshot as webshot takes the html file as the input.
