### ISSUE TITLE
Possible bug with circular graphs

### ISSUE THREAD

**Issue by seoanezonjic** [neuhausi/canvasXpress#99]
Hi @neuhausi 
It's a long time since I've report the last issue. I have an old project in which I use the circular graphs in a lot of cases and for this reason I've ask you your help several times with this kind of graph. I've resumed this project and updated my reports with the last CanvasXpress version. One of my representations look as following:
![cX-obj_29_](https://user-images.githubusercontent.com/4126037/89165124-65447b00-d578-11ea-82c7-fd82918bcca2.png)
As you can see, the samples have a shift and they overlap between them (see the R_Clon overlay) even one of the sample slots is empty. I think that it's a bug, but maybe I've misconfigured the chart. How do you think I could fix this representation?

**Comment by neuhausi** [comment]
Working on it.

**Comment by neuhausi** [comment]
Fixed in Version 29.2

![cX-obj_29_-1](https://user-images.githubusercontent.com/254923/89310331-8a052500-d642-11ea-93fd-6ea76e50a83e.png)
